# coding=utf-8
# pylint: disable=line-too-long,too-many-lines,invalid-character-zero-width-space,invalid-name,redefined-builtin
"""Module contains Text Objects"""
from enna_hcp_configuration.texts import TextObject

formatting__address___center = TextObject(bs_BA="Gradski centar", cs_CZ="Centrum města", da_DK="Bycentrum", de_DE="Stadtzentrum", el_GR="Κέντρο της πόλης", en_GB="Town centre", es_ES="Centro de la ciudad", fi_FI="Kaupungin keskusta", fr_FR="Centre-ville", hr_HR="Centar grada", hu_HU="Városközpont", it_IT="Centro città", nl_NL="Stadscentrum", no_NO="Bysentrum", pl_PL="Śródmieście", pt_PT="Centro da cidade", ro_RO="Centru oraş", ru_RU="Центр города", sk_SK="Centrum mesta", sl_SI="Center mesta", sr_RS="Centar grada", sv_SE="Stadscentrum", tr_TR="Şehir merkezi", uk_UA="Центр міста")
formatting__address___offroad = TextObject(bs_BA="Van puta", cs_CZ="Offroad", da_DK="Offroad", de_DE="Offroad", el_GR="Εκτός δρόμου", en_GB="Offroad", es_ES="Offroad", fi_FI="Offroad", fr_FR="Offroad", hr_HR="Offroad", hu_HU="Offroad", it_IT="Offroad", nl_NL="Offroad", no_NO="Offroad", pl_PL="Offroad", pt_PT="Offroad", ro_RO="Offroad", ru_RU="Offroad", sk_SK="Offroad", sl_SI="Offroad", sr_RS="Offroad", sv_SE="Offroad", tr_TR="Offroad", uk_UA="Поза дорогою")
formatting__address___osp = TextObject(bs_BA="On-Street Parking", cs_CZ="On-Street Parking", da_DK="On-Street Parking", de_DE="On-Street Parking", el_GR="On-Street Parking", en_GB="On-street parking", es_ES="On-Street Parking", fi_FI="On-Street Parking", fr_FR="On-Street Parking", hr_HR="On-Street Parking", hu_HU="On-Street Parking", it_IT="On-Street Parking", nl_NL="On-Street Parking", no_NO="On-Street Parking", pl_PL="On-Street Parking", pt_PT="On-Street Parking", ro_RO="On-Street Parking", ru_RU="On-Street Parking", sk_SK="On-Street Parking", sl_SI="On-Street Parking", sr_RS="On-Street Parking", sv_SE="On-Street Parking", tr_TR="On-Street Parking", uk_UA="On-Street Parking")
formatting__meridiem___am = TextObject(bs_BA="AM", cs_CZ="AM", da_DK="AM", de_DE="AM", el_GR="AM", en_GB="AM", es_ES="AM", fi_FI="AM", fr_FR="AM", hr_HR="AM", hu_HU="AM", it_IT="AM", nl_NL="AM", no_NO="AM", pl_PL="AM", pt_PT="AM", ro_RO="AM", ru_RU="AM", sk_SK="AM", sl_SI="AM", sr_RS="AM", sv_SE="AM", tr_TR="AM", uk_UA="AM")
formatting__meridiem___pm = TextObject(bs_BA="PM", cs_CZ="PM", da_DK="PM", de_DE="PM", el_GR="PM", en_GB="PM", es_ES="PM", fi_FI="PM", fr_FR="PM", hr_HR="PM", hu_HU="PM", it_IT="PM", nl_NL="PM", no_NO="PM", pl_PL="PM", pt_PT="PM", ro_RO="PM", ru_RU="PM", sk_SK="PM", sl_SI="PM", sr_RS="PM", sv_SE="PM", tr_TR="PM", uk_UA="PM")
formatting__prefix___in = TextObject(bs_BA="u", cs_CZ="za", da_DK="om", de_DE="in", el_GR="σε", en_GB="in", es_ES="en", fi_FI="​", fr_FR="dans", hr_HR="za", hu_HU="múlv", it_IT="fra", nl_NL="over", no_NO="om", pl_PL="za", pt_PT="em", ro_RO="în", ru_RU="чрз", sk_SK="o", sl_SI="čez", sr_RS="za", sv_SE="om", tr_TR="​", uk_UA="за")
formatting__prefix___minus = TextObject(bs_BA="-", cs_CZ="-", da_DK="-", de_DE="-", el_GR="-", en_GB="-", es_ES="-", fi_FI="-", fr_FR="-", hr_HR="-", hu_HU="-", it_IT="-", nl_NL="-", no_NO="-", pl_PL="-", pt_PT="-", ro_RO="-", ru_RU="-", sk_SK="-", sl_SI="-", sr_RS="-", sv_SE="-", tr_TR="-", uk_UA="-")
formatting__prefix___plus = TextObject(bs_BA="+", cs_CZ="+", da_DK="+", de_DE="+", el_GR="+", en_GB="+", es_ES="+", fi_FI="+", fr_FR="+", hr_HR="+", hu_HU="+", it_IT="+", nl_NL="+", no_NO="+", pl_PL="+", pt_PT="+", ro_RO="+", ru_RU="+", sk_SK="+", sl_SI="+", sr_RS="+", sv_SE="+", tr_TR="+", uk_UA="+")
formatting__unit___foot = TextObject(bs_BA="ft", cs_CZ="ft", da_DK="ft", de_DE="ft", el_GR="ft", en_GB="ft", es_ES="ft", fi_FI="ft", fr_FR="ft", hr_HR="ft", hu_HU="ft", it_IT="ft", nl_NL="ft", no_NO="ft", pl_PL="ft", pt_PT="ft", ro_RO="ft", ru_RU="ft", sk_SK="ft", sl_SI="ft", sr_RS="ft", sv_SE="ft", tr_TR="ft", uk_UA="ft")
formatting__unit___hours = TextObject(bs_BA="h", cs_CZ="h", da_DK="h", de_DE="h", el_GR="h", en_GB="h", es_ES="h", fi_FI="h", fr_FR="h", hr_HR="h", hu_HU="h", it_IT="h", nl_NL="h", no_NO="h", pl_PL="h", pt_PT="h", ro_RO="h", ru_RU="h", sk_SK="h", sl_SI="h", sr_RS="h", sv_SE="h", tr_TR="h", uk_UA="h")
formatting__unit___kilometers = TextObject(bs_BA="km", cs_CZ="km", da_DK="km", de_DE="km", el_GR="km", en_GB="km", es_ES="km", fi_FI="km", fr_FR="km", hr_HR="km", hu_HU="km", it_IT="km", nl_NL="km", no_NO="km", pl_PL="km", pt_PT="km", ro_RO="km", ru_RU="km", sk_SK="km", sl_SI="km", sr_RS="km", sv_SE="km", tr_TR="km", uk_UA="km")
formatting__unit___kilowatt = TextObject(bs_BA="kW", cs_CZ="kW", da_DK="kW", de_DE="kW", el_GR="kW", en_GB="kW", es_ES="kW", fi_FI="kW", fr_FR="kW", hr_HR="kW", hu_HU="kW", it_IT="kW", nl_NL="kW", no_NO="kW", pl_PL="kW", pt_PT="kW", ro_RO="kW", ru_RU="kW", sk_SK="kW", sl_SI="kW", sr_RS="kW", sv_SE="kW", tr_TR="kW", uk_UA="kW")
formatting__unit___meters = TextObject(bs_BA="m", cs_CZ="m", da_DK="m", de_DE="m", el_GR="m", en_GB="m", es_ES="m", fi_FI="m", fr_FR="m", hr_HR="m", hu_HU="m", it_IT="m", nl_NL="m", no_NO="m", pl_PL="m", pt_PT="m", ro_RO="m", ru_RU="m", sk_SK="m", sl_SI="m", sr_RS="m", sv_SE="m", tr_TR="m", uk_UA="m")
formatting__unit___miles = TextObject(bs_BA="mi", cs_CZ="mi", da_DK="mi", de_DE="mi", el_GR="mi", en_GB="mi", es_ES="mi", fi_FI="mi", fr_FR="mi", hr_HR="mi", hu_HU="mi", it_IT="mi", nl_NL="mi", no_NO="mi", pl_PL="mi", pt_PT="mi", ro_RO="mi", ru_RU="mi", sk_SK="mi", sl_SI="mi", sr_RS="mi", sv_SE="mi", tr_TR="mi", uk_UA="mi")
formatting__unit___milliseconds = TextObject(bs_BA="ms", cs_CZ="ms", da_DK="ms", de_DE="ms", el_GR="ms", en_GB="ms", es_ES="ms", fi_FI="ms", fr_FR="ms", hr_HR="ms", hu_HU="ms", it_IT="ms", nl_NL="ms", no_NO="ms", pl_PL="ms", pt_PT="ms", ro_RO="ms", ru_RU="ms", sk_SK="ms", sl_SI="ms", sr_RS="ms", sv_SE="ms", tr_TR="ms", uk_UA="ms")
formatting__unit___minutes = TextObject(bs_BA="min", cs_CZ="min", da_DK="min", de_DE="min", el_GR="min", en_GB="min", es_ES="min", fi_FI="min", fr_FR="min", hr_HR="min", hu_HU="perc", it_IT="min", nl_NL="min", no_NO="min", pl_PL="min", pt_PT="min", ro_RO="min", ru_RU="min", sk_SK="min", sl_SI="min", sr_RS="min", sv_SE="min", tr_TR="dak", uk_UA="min")
formatting__unit___percent = TextObject(bs_BA="%", cs_CZ="%", da_DK="%", de_DE="%", el_GR="%", en_GB="%", es_ES="%", fi_FI="%", fr_FR="%", hr_HR="%", hu_HU="%", it_IT="%", nl_NL="%", no_NO="%", pl_PL="%", pt_PT="%", ro_RO="%", ru_RU="%", sk_SK="%", sl_SI="%", sr_RS="%", sv_SE="%", tr_TR="%", uk_UA="%")
formatting__unit___seconds = TextObject(bs_BA="s", cs_CZ="s", da_DK="s", de_DE="s", el_GR="s", en_GB="s", es_ES="s", fi_FI="s", fr_FR="s", hr_HR="s", hu_HU="s", it_IT="s", nl_NL="s", no_NO="s", pl_PL="s", pt_PT="s", ro_RO="s", ru_RU="s", sk_SK="s", sl_SI="s", sr_RS="s", sv_SE="s", tr_TR="s", uk_UA="s")
formatting__unit___yards = TextObject(bs_BA="yd", cs_CZ="yd", da_DK="yd", de_DE="yd", el_GR="yd", en_GB="yd", es_ES="yd", fi_FI="yd", fr_FR="yd", hr_HR="yd", hu_HU="yd", it_IT="yd", nl_NL="yd", no_NO="yd", pl_PL="yd", pt_PT="yd", ro_RO="yd", ru_RU="yd", sk_SK="yd", sl_SI="yd", sr_RS="yd", sv_SE="yd", tr_TR="yd", uk_UA="yd")
