# coding=utf-8
# pylint: disable=line-too-long,too-many-lines,invalid-character-zero-width-space,invalid-name,redefined-builtin
"""Module contains Text Objects"""
from enna_hcp_configuration.texts import TextObject

texttool_globals_aosp_settings_list_item_subtext___osd_app_name = TextObject(bs_BA="Dizajn mirovanja", cs_CZ="Design Standby", da_DK="Standbydesign", de_DE="Standby-Design", el_GR="Οθόνη αναμονής", en_GB="Standby design", es_ES="Diseño standby", fi_FI="Standby-ulkoasu", fr_FR="Design du mode veille", hr_HR="Standby dizajn", hu_HU="Készenléti dizájn", it_IT="Design standby", nl_NL="Standby-design", no_NO="Standby-design", pl_PL="Design spoczynkowy", pt_PT="Standby-Design", ro_RO="Design standby", ru_RU="Режим ожидания", sk_SK="Standby-Design", sl_SI="Prikaz v stanju pripravljenosti", sr_RS="Standby dizajn", sv_SE="Standby-design", tr_TR="Bekleme tasarımı", uk_UA="Режим очікування")
texttool_globals_aosp_settings_list_item_text___osd_title = TextObject(bs_BA="Open Source Software Notice", cs_CZ="Open Source Software Notice", da_DK="Open Source Software Notice", de_DE="Open Source Software Notice", el_GR="Open Source Software Notice", en_GB="Open Source Software Notice", es_ES="Open Source Software Notice", fi_FI="Open Source Software Notice", fr_FR="Open Source Software Notice", hr_HR="Open Source Software Notice", hu_HU="Open Source Software Notice", it_IT="Open Source Software Notice", nl_NL="Open Source Software Notice", no_NO="Open Source Software Notice", pl_PL="Open Source Software Notice", pt_PT="Open Source Software Notice", ro_RO="Open Source Software Notice", ru_RU="Open Source Software Notice", sk_SK="Open Source Software Notice", sl_SI="Open Source Software Notice", sr_RS="Open Source Software Notice", sv_SE="Open Source Software Notice", tr_TR="Open Source Software Notice", uk_UA="Open Source Software Notice")
texttool_globals_application_label___app_name = TextObject(bs_BA="Dizajn mirovanja", cs_CZ="Design Standby", da_DK="Standbydesign", de_DE="Standby-Design", el_GR="Οθόνη αναμονής", en_GB="Standby design", es_ES="Diseño standby", fi_FI="Standby-ulkoasu", fr_FR="Design du mode veille", hr_HR="Standby dizajn", hu_HU="Készenléti dizájn", it_IT="Design standby", nl_NL="Standby-design", no_NO="Standby-design", pl_PL="Design spoczynkowy", pt_PT="Standby-Design", ro_RO="Design standby", ru_RU="Режим ожидания", sk_SK="Standby-Design", sl_SI="Prikaz v stanju pripravljenosti", sr_RS="Standby dizajn", sv_SE="Standby-design", tr_TR="Bekleme tasarımı", uk_UA="Режим очікування")
title_digital_decors = TextObject(bs_BA="Dizajn mirovanja", cs_CZ="Design Standby", da_DK="Standbydesign", de_DE="Standby-Design", el_GR="Οθόνη αναμονής", en_GB="Standby design", es_ES="Diseño standby", fi_FI="Standby-ulkoasu", fr_FR="Design du mode veille", hr_HR="Standby dizajn", hu_HU="Készenléti dizájn", it_IT="Design standby", nl_NL="Standby-design", no_NO="Standby-design", pl_PL="Design spoczynkowy", pt_PT="Standby-Design", ro_RO="Design standby", ru_RU="Режим ожидания", sk_SK="Standby-Design", sl_SI="Prikaz v stanju pripravljenosti", sr_RS="Standby dizajn", sv_SE="Standby-design", tr_TR="Bekleme tasarımı", uk_UA="Режим очікування")
