# coding=utf-8
# pylint: disable=line-too-long,too-many-lines,invalid-character-zero-width-space,invalid-name,redefined-builtin
"""Module contains Text Objects"""
from enna_hcp_configuration.texts import TextObject

texttool_globals_application_label___osd_app_name = TextObject(bs_BA="Open Source Software Notice", cs_CZ="Open Source Software Notice", da_DK="Open Source Software Notice", de_DE="Open Source Software Notice", el_GR="Open Source Software Notice", en_GB="Open Source Software Notice", es_ES="Open Source Software Notice", fi_FI="Open Source Software Notice", fr_FR="Open Source Software Notice", hr_HR="Open Source Software Notice", hu_HU="Open Source Software Notice", it_IT="Open Source Software Notice", nl_NL="Open Source Software Notice", no_NO="Open Source Software Notice", pl_PL="Open Source Software Notice", pt_PT="Open Source Software Notice", ro_RO="Open Source Software Notice", ru_RU="Open Source Software Notice", sk_SK="Open Source Software Notice", sl_SI="Open Source Software Notice", sr_RS="Open Source Software Notice", sv_SE="Open Source Software Notice", tr_TR="Open Source Software Notice", uk_UA="Open Source Software Notice")
texttool_globals_hmisdk_blockable_text___hmisdk__blockable_text_view_blocking_text = TextObject(bs_BA="Ograničeno rukovanje u toku vožnje.", cs_CZ="Omezená obsluha během jízdy.", da_DK="Begrænset betjening under kørsel.", de_DE="Eingeschränkte Bedienung während der Fahrt.", el_GR="Περιορισμένος χειρισμός κατά τη διάρκεια της οδήγησης.", en_GB="For your safety, limited operation while driving.", es_ES="Manejo limitado durante la marcha.", fi_FI="Rajoitettu käyttö ajon aikana.", fr_FR="Utilisation restreinte pendant la conduite.", hr_HR="Ograničeno rukovanje tijekom vožnje.", hu_HU="Korlátozott használat menet közben.", it_IT="Utilizzo limitato durante la marcia.", nl_NL="Beperkte bediening tijdens het rijden.", no_NO="Betjening er begrenset under kjøring.", pl_PL="Ograniczona obsługa podczas jazdy.", pt_PT="Acionamento com restrições durante a circulação.", ro_RO="Operare limitată în timpul deplasării.", ru_RU="Во время движения управление ограничено.", sk_SK="Obmedzená obsluha počas jazdy.", sl_SI="Omejeno upravljanje med vožnjo.", sr_RS="Ograničeno rukovanje u toku vožnje.", sv_SE="Begränsad användning under körning.", tr_TR="Sürüş sırasında sınırlı kullanım.", uk_UA="Під час руху керування обмежено.")
texttool_globals_hmisdk_blocking_disclaimer___hmisdk__disclaimer_text_blocking = TextObject(bs_BA="Ograničeno rukovanje u toku vožnje.", cs_CZ="Omezená obsluha během jízdy.", da_DK="Begrænset betjening under kørsel.", de_DE="Eingeschränkte Bedienung während der Fahrt.", el_GR="Περιορισμένος χειρισμός κατά τη διάρκεια της οδήγησης.", en_GB="For your safety, limited operation while driving.", es_ES="Manejo limitado durante la marcha.", fi_FI="Rajoitettu käyttö ajon aikana.", fr_FR="Utilisation restreinte pendant la conduite.", hr_HR="Ograničeno rukovanje tijekom vožnje.", hu_HU="Korlátozott használat menet közben.", it_IT="Utilizzo limitato durante la marcia.", nl_NL="Beperkte bediening tijdens het rijden.", no_NO="Betjening er begrenset under kjøring.", pl_PL="Ograniczona obsługa podczas jazdy.", pt_PT="Acionamento com restrições durante a circulação.", ro_RO="Operare limitată în timpul deplasării.", ru_RU="Во время движения управление ограничено.", sk_SK="Obmedzená obsluha počas jazdy.", sl_SI="Omejeno upravljanje med vožnjo.", sr_RS="Ograničeno rukovanje u toku vožnje.", sv_SE="Begränsad användning under körning.", tr_TR="Sürüş sırasında sınırlı kullanım.", uk_UA="Під час руху керування обмежено.")
texttool_globals_toast___hmisdk__default_disabled_reason_text = TextObject(bs_BA="Sistem trenutno nije raspoloživ.", cs_CZ="Systém je nyní nedostupný.", da_DK="System p.t. ikke tilgængeligt.", de_DE="Das System ist zurzeit nicht verfügbar.", el_GR="Το σύστημα προς το παρόν δεν είναι διαθέσιμο.", en_GB="The system is currently unavailable.", es_ES="El sistema no está disponible actualmente.", fi_FI="Järjestelmä ei ole tällä hetkellä käytettävissä.", fr_FR="Le système n'est pas disponible actuellement.", hr_HR="Sustav trenutačno nije raspoloživ.", hu_HU="A rendszer jelenleg nem áll rendelkezésre.", it_IT="Il sistema non è disponibile al momento.", nl_NL="Het systeem is momenteel niet beschikbaar.", no_NO="Systemet er ikke tilgjengelig for øyeblikket.", pl_PL="System jest obecnie niedostępny.", pt_PT="O sistema não está disponível de momento.", ro_RO="Sistemul nu este momentan disponibil.", ru_RU="Система сейчас недоступна.", sk_SK="Systém momentálne nie je k dispozícii.", sl_SI="Sistem trenutno ni na voljo.", sr_RS="Sistem trenutno nije dostupan.", sv_SE="Systemet är inte tillgängligt för närvarande.", tr_TR="Sistem şu anda mevcut değil.", uk_UA="Система наразі недоступна.")
