# -*- coding: utf-8 -*-
"""Created on 23.06.2023.

@project: enna_kwd_testing.
@author: DYX34ZN: Jakob Kein.

Contains concrete base class for stimulation factory.
"""

import logging

import enna.core.config
import enna.core.interfaces.testing

from enna_kwd_testing.stimulations.base.testcase_baseclass import StimulationBase

MODULE_LOGGER = logging.getLogger(__name__)


class TestcaseFactory(enna.core.interfaces.testing.StimulationFactory):
	"""Generic factory to generate testcases as stimulations from given test specification dictionary."""

	def __init__(self, reporting, adb, android_hmi, testspeclist, *args, **kwargs):
		"""Initialize testcase factory object.

		:param enna.core.reporting reporting: Instance of reporting interface
		:param enna.data_interfaces.adb.interface.Interface adb: instance of interface to Android Debug Bridge
		:param enna_st12.data_interfaces.android_hmi.interface.Interface android_hmi: instance of uiautomator
		:param testspeclist: list of testcases as dictionary
		:type testspeclist: list[dict]
		:param tuple args: Arguments for DependencyFactory
		:param dict kwargs: Keyword arguments for DependencyFactory
		"""
		super().__init__(reporting, *args)
		self._test_spec_list = testspeclist
		self.initialized_keyword_stims = kwargs
		self._adb = adb
		self._android_hmi = android_hmi
		self.__generate()

	@staticmethod
	def __exctract_action_teststeps(testcase: dict) -> list:
		"""Extract teststeps from test specification and match actions and expected results.

		:param testcase: testcase to extract teststeps from
		:type testcase: dict
		:return: list of teststeps
		:rtype: list
		"""
		result_list = []
		for index, _ in enumerate(testcase["action"], start=1):
			step_dict = {"action": testcase["action"][index - 1], "results": None}
			teststep_results = []
			for expected_result in testcase["expectedresult"]:
				if str(expected_result["step"]).startswith(str(index)):
					teststep_results.append(expected_result)
				step_dict.update({"results": teststep_results})
			result_list.append(step_dict)
		return result_list

	@staticmethod
	def __extract_precondition_teststeps(testcase: dict) -> list:
		"""Extract preconditions from test specification.

		:param testcase: testcase to extract precondition from
		:type testcase: dict
		:return: list of preconditions
		:rtype: list
		"""
		try:
			return testcase["precondition"]
		except KeyError:
			MODULE_LOGGER.info("No preconditions specified.")
			return []

	@staticmethod
	def __extract_postcondition_teststeps(testcase):
		"""Extract postconditions from test specification.

		:param testcase: testcase to extract postcondition from
		:type testcase: dict
		:return: list of postconditions
		:rtype: list
		"""
		try:
			return testcase["postcondition"]
		except KeyError:
			MODULE_LOGGER.info("No postconditions specified.")
			return []

	def __report_formatter(self, steps: list) -> str:
		"""Formatting extracted steps of Test Case to readable text for reporting.

		:param steps: steps of pre-condition, action or post-condition
		:return: formatted text
		"""
		formatted_text = ""
		for step in steps:
			if isinstance(step, list):
				self.__report_formatter(step)
			elif isinstance(step, dict):
				step_number = step.get("step", "error")
				step_keyword = step.get("name", "error")
				step_values = ", ".join(f"{key}: {value}" for key, value in step.get("values", {}).items()) if isinstance(step.get("values", {}), dict) else "error"
				step_stimulation = step.get("automation", "error")
				formatted_text += f"Step {step_number}: {step_keyword} ({step_values})".ljust(100) + f"Stimulation = {step_stimulation}\n"
			else:
				formatted_text += "Error on formatting Step!\n"
		return formatted_text[:-2]


	def __generate(self) -> None:
		"""Generate testcases as stimulations.

		The stimulations will be generated by parameterizing a stimulation object with following values:
		1. reporting: enna.core.reporting.interface.Interface: Instance of the reporting interface for the stimulation -> Constant
		2. preconditions: list[dict] preconditions: Contains the teststep values from .json source
		3. actions: list[dict] actions: Contains the teststep values from .json source
		4. results: list[dict] results: Contains the teststep values from .json source
		5. postconditions: list[dict] postconditions: Contains the teststep values from .json source
		6. initialized_keyword_objects: Contains all necessary, initialized component objects which are necessary for this specific testcase
		7. test_ids: enna.core.interfaces.testing.TestCaseSpecification test_ids: Contains an enna test specification object which holds test specification attributes

		:raise enna_kwd_testing.factories.exceptions.TestSpecificationException: When the test specification is not consistent for testautomation.
		"""
		for testcase in self._test_spec_list:
			preconditions_from_testcase = self.__extract_precondition_teststeps(testcase)
			postconditions_from_testcase = self.__extract_postcondition_teststeps(testcase)
			teststeps = self.__exctract_action_teststeps(testcase)
			test_spec = enna.core.interfaces.testing.TestCaseSpecification(
				id=testcase["testcase_id"],
				description=" description: " + testcase["testcase_description"],
				precondition=self.__report_formatter(preconditions_from_testcase),
				action=self.__report_formatter(testcase.get("action", [])),
				expected_result=self.__report_formatter(testcase.get("expectedresult", [])),
				postcondition=self.__report_formatter(postconditions_from_testcase),
				name=testcase["testcase_name"]
			)
			MODULE_LOGGER.info("COLLECTED following preconditions, actions and postconditions.")
			counter = 0
			stimulation = type(str(counter), (StimulationBase,), {})
			self._created_objects.append(
				stimulation(
					reporting=self._reporting,
					adb = self._adb,
					android_hmi=self._android_hmi,
					preconditions=preconditions_from_testcase,
					teststeps=teststeps,
					postconditions=postconditions_from_testcase,
					initialized_keyword_objects=self.initialized_keyword_stims,
					test_ids=test_spec
				))
			counter += 1
