# -*- coding: utf-8 -*-
"""Contains start for generic campaign which is generated by .json source."""
from pathlib import Path

import enna.core.campaign
import enna.core.campaign_runner
import enna.core.config
import enna.core.custom_extensions
import enna.core.deployment.dependency_manager

import enna_kwd_testing.custom_types
import enna_kwd_testing.campaigns.alignments.alignment
import enna_kwd_testing.definitions
import enna_kwd_testing.utilities.stimulation_factory_generator.generator
import enna_kwd_testing.utilities.testset.loader


enna.core.config.INFOTAINMENT_SYSTEM.system_language = enna_kwd_testing.custom_types.Language["EN_GB"]
CONFIG = enna.core.config.get("enna_kwd_testing.campaigns.common")


def run(folder: Path | str = None, login: tuple | None = None) -> None:
	"""Run campaign with parameters.

	:param folder: folder for testset input
	:param login: tuple with host_user,host_password,db_user,db_password
	"""
	if folder is None:
		folder = Path(CONFIG["input_folder"]).absolute()
	folder = Path(folder)
	testcase_list = enna_kwd_testing.utilities.testset.loader.load_testset_from_files(folder)

	camp = enna.core.campaign.Campaign("keyword_driven_testing")

	camp.add_passive_test("enna_kwd_testing.passive.tests.TraceLogger")
	camp.start_passive_tests()

	initialization = camp.add_testgroup("INITIALIZATION")

	startup = initialization.add_testgroup("Startup Bench")
	startup.add_testcase("enna_kwd_testing.macros.testbench_preparations.Startup")

	read_test_setup = initialization.add_testgroup("Reading Configuration Test Setup")
	read_test_setup.add_testcase("enna_kwd_testing.stimulations.adb.general.ReportingAllPackagesAndVersions")

	prepare = initialization.add_testgroup("Prepare Test Bench State")
	prepare.add_testcase("enna_kwd_testing.macros.testbench_preparations.PrepareConnectCampaign")

	tests = camp.add_testgroup("Testing")
	base_factory_path = enna_kwd_testing.utilities.stimulation_factory_generator.generator.generate(testcase_list)
	tests.add_testcase_factory(base_factory_path, testset_input_folder=Path(folder))

	enna.core.campaign_runner.start_campaign(camp, enna_kwd_testing.campaigns.alignments.alignment.DEFAULT_ALIGNMENT)


if __name__ == "__main__":
	run()
