# coding=utf-8
# pylint: disable=line-too-long,too-many-lines,invalid-character-zero-width-space,invalid-name,redefined-builtin
"""Module contains Text Objects"""
from enna_hcp_configuration.texts import TextObject

hcp3_ext_connection_manager = TextObject(bs_BA="Menadžer povezivanja", cs_CZ="Manažer spojení", da_DK="Forbindelses­manager", de_DE="Verbindungsmanager", el_GR="Διαχειριστής συνδέσεων", en_GB="Connection manager", es_ES="Gestor de conexiones", fi_FI="Yhteyksien hallinta", fr_FR="Gestionnaire de connexion", hr_HR="Connection manager", hu_HU="Összeköttetés-menedzser", it_IT="Manager collegamento", nl_NL="Verbindingen", no_NO="Tilkoblingsmanager", pl_PL="Manager połączeń", pt_PT="Gestor de ligações", ro_RO="Manager conexiuni", ru_RU="Менеджер подключений", sk_SK="Manažér spojenia", sl_SI="Upravitelj povezav", sr_RS="Menadžer za povezivanje", sv_SE="Anslutningshanterare", tr_TR="Bağlantı yöneticisi", uk_UA="Диспетчер підключень")
hcp3_ext_lock_active = TextObject(bs_BA="Ograničeno rukovanje u toku vožnje.", cs_CZ="Omezená obsluha během jízdy.", da_DK="Begrænset betjening under kørsel.", de_DE="Eingeschränkte Bedienung während der Fahrt.", el_GR="Περιορισμένος χειρισμός κατά τη διάρκεια της οδήγησης.", en_GB="For your safety, limited operation while driving.", es_ES="Manejo limitado durante la marcha.", fi_FI="Rajoitettu käyttö ajon aikana.", fr_FR="Utilisation restreinte pendant la conduite.", hr_HR="Ograničeno rukovanje tijekom vožnje.", hu_HU="Korlátozott használat menet közben.", it_IT="Utilizzo limitato durante la marcia.", nl_NL="Beperkte bediening tijdens het rijden.", no_NO="Betjening er begrenset under kjøring.", pl_PL="Ograniczona obsługa podczas jazdy.", pt_PT="Acionamento com restrições durante a circulação.", ro_RO="Operare limitată în timpul deplasării.", ru_RU="Во время движения управление ограничено.", sk_SK="Obmedzená obsluha počas jazdy.", sl_SI="Omejeno upravljanje med vožnjo.", sr_RS="Ograničeno rukovanje u toku vožnje.", sv_SE="Begränsad användning under körning.", tr_TR="Sürüş sırasında sınırlı kullanım.", uk_UA="Під час руху керування обмежено.")
hcp3_ext_media_settings_disclaimer_of_liability = TextObject(bs_BA="Isključenje odgovornosti", cs_CZ="Vyloučení odpovědnosti", da_DK="Ansvarsfrihed", de_DE="Haftungsausschluss", el_GR="Αποποίηση ευθυνών", en_GB="Disclaimer", es_ES="Exención de responsabilidad", fi_FI="Vastuuvapauslauseke", fr_FR="Clause de non-responsabilité", hr_HR="Isključenje od odgovornosti", hu_HU="Jogi nyilatkozat", it_IT="Esclusione di responsabilità", nl_NL="Vrijwaringsclausule", no_NO="Ansvarsfraskrivelse", pl_PL="Wyłączenie odpowiedzialności", pt_PT="Isenção de responsabilidade", ro_RO="Exonerarea răspunderii", ru_RU="Отказ от ответственности", sk_SK="Vylúčenie zodpovednosti", sl_SI="Izključitev odgovornosti", sr_RS="Odricanje odgovornosti", sv_SE="Ansvarsfriskrivning", tr_TR="Sorumluluk reddi", uk_UA="Відмова від відповідальності")
hcp3_ext_media_settings_imprint = TextObject(bs_BA="Impresum", cs_CZ="Impressum", da_DK="Kolofon", de_DE="Impressum", el_GR="Στοιχεία έκδοσης", en_GB="About us", es_ES="Nota legal", fi_FI="Julkaisutiedot", fr_FR="Mentions légales", hr_HR="Impresum", hu_HU="Impresszum", it_IT="Informazioni societarie (Impressum)", nl_NL="Impressum", no_NO="Utgiverinformasjon", pl_PL="Stopka redakcyjna", pt_PT="Aviso legal", ro_RO="Caseta redacţiei", ru_RU="Импрессум", sk_SK="Tiráž", sl_SI="Impresum", sr_RS="Impresum", sv_SE="Tryckinformation", tr_TR="Künye", uk_UA="Вихідні дані")
hcp3_ext_media_settings_privacy_notice = TextObject(bs_BA="Napomene o zaštiti podataka", cs_CZ="Pokyny k ochraně dat", da_DK="Databeskyttelsesinformationer", de_DE="Datenschutzhinweise", el_GR="Υποδείξεις προστασίας δεδομένων προσωπικού χαρακτήρα", en_GB="Data protection notes", es_ES="Aviso de privacidad", fi_FI="Tietosuojaohjeet", fr_FR="Informations relatives à la protection des données", hr_HR="Napomene o zaštiti podataka", hu_HU="Adatvédelmi irányelvek", it_IT="Avvertenze sulla protezione dati", nl_NL="Privacyrichtlijnen", no_NO="Informasjon om personvern", pl_PL="Polityka prywatności", pt_PT="Política de proteção de dados", ro_RO="Informaţii protecţia datelor", ru_RU="Примечания по защите персональных данных", sk_SK="Pokyny k ochrane údajov", sl_SI="Napotki za varovanje podatkov", sr_RS="Napomene o zaštiti podataka", sv_SE="Dataskydd", tr_TR="Veri koruma bilgileri", uk_UA="Вказівки із захисту даних")
hcp3_ext_media_settings_terms_of_use = TextObject(bs_BA="Napomene o korištenju", cs_CZ="Pokyny k užívání", da_DK="Anvendelsesinformationer", de_DE="Nutzungshinweise", el_GR="Οδηγίες σχετικά με τη χρήση", en_GB="Usage information", es_ES="Indicaciones de uso", fi_FI="Käyttöohjeita", fr_FR="Conditions d'utilisation", hr_HR="Napomene za korištenje", hu_HU="Felhasználási tudnivalók", it_IT="Avvertenze per l'utilizzo", nl_NL="Gebruiksaanwijzingen", no_NO="Informasjon om bruk", pl_PL="Wskazówki dotyczące użytkowania", pt_PT="Instruções de utilização", ro_RO="Indicaţii de utilizare", ru_RU="Примечания относительно пользования", sk_SK="Pokyny pre použitie", sl_SI="Napotki za uporabo", sr_RS="Napomene o korišćenju", sv_SE="Användningsinformation", tr_TR="Kullanım koşulları", uk_UA="Вказівки з користування")
hcp3_ext_settings = TextObject(bs_BA="Postavke", cs_CZ="Nastavení", da_DK="Indstillinger", de_DE="Einstellungen", el_GR="Ρυθμίσεις", en_GB="Settings", es_ES="Ajustes", fi_FI="Asetukset", fr_FR="Réglages", hr_HR="Postavke", hu_HU="Beállítások", it_IT="Impostazioni", nl_NL="Instellingen", no_NO="Innstillinger", pl_PL="Ustawienia", pt_PT="Ajustes", ro_RO="Setări", ru_RU="Настройки", sk_SK="Nastavenia", sl_SI="Nastavitve", sr_RS="Podešavanja", sv_SE="Inställningar", tr_TR="Ayarlar", uk_UA="Настройки")
hcp3_ext_sound_setting = TextObject(bs_BA="Postavke zvuka", cs_CZ="Nastavení zvuku", da_DK="Lydindstillinger", de_DE="Klangeinstellungen", el_GR="Ρυθμίσεις ήχου", en_GB="Sound settings", es_ES="Ajustes del sonido", fi_FI="Ääniasetukset", fr_FR="Réglages sonores", hr_HR="Namještanja zvuka", hu_HU="Hangbeállítások", it_IT="Impostazioni Suono", nl_NL="Klankinstellingen", no_NO="Toneinnstillinger", pl_PL="Ustawienia dźwięku", pt_PT="Ajustes do som", ro_RO="Setări sunet", ru_RU="Настройки звучания", sk_SK="Nastavenia zvuku", sl_SI="Nastavitve zvoka", sr_RS="Podešavanja zvuka", sv_SE="Ljudinställningar", tr_TR="Ses ayarları", uk_UA="Настройки звуку")
