# -*- coding: utf-8 -*-
"""Module contains xpath of car app."""
from . import XpathString


# pylint: disable=line-too-long
NAME = XpathString("//*[contains(@text,'Store')]")
INIT_TITLE = XpathString("//*[@resource-id='com.harman.ignite.appstore.audi:id/init_screen'] and //*[contains(@content-desc, 'com.harman.ignite.appstore.audi:string/app_name')]")
LOADING_SCREEN = XpathString("//*[contains(@resource-id,'com.harman.ignite.appstore.audi:id/initTextView')][contains(@text, 'loading')]")
CAR_FUNCTIONALITY = XpathString("//*[@class='android.widget.HorizontalScrollView']/*/*[@class='android.widget.LinearLayout'][@package='com.harman.ignite.appstore.audi'][@index=0]")
APPS = XpathString("//*[@class='android.widget.HorizontalScrollView']/*/*[@class='android.widget.LinearLayout'][@package='com.harman.ignite.appstore.audi'][@index=1]")
MY_APPLICATIONS = XpathString("//*[@class='android.widget.HorizontalScrollView']/*/*[@class='android.widget.LinearLayout'][@package='com.harman.ignite.appstore.audi'][@index=2]")
CAR_FUNCTIONALITY_SELECTED_TITLE = XpathString(
	clu46="//*[@content-desc='store_tablayout_first_tab_desc'][@selected='true']",
	clu53=CAR_FUNCTIONALITY.get() + "//*[@class='android.widget.TextView'][@selected='true']"
)
APPS_SELECTED_TITLE = XpathString(APPS.get() + "//*[@class='android.widget.TextView'][@selected='true']")
MY_APPLICATIONS_SELECTED_TITLE = XpathString(MY_APPLICATIONS.get() + "//*[@class='android.widget.TextView'][@selected='true']")
BACK_BUTTON = XpathString("//*[contains(@content-desc, 'Back')]")
APP_DESCRIPTION = XpathString("//*[contains(@content-desc, 'about_this_app')]")
SEARCH_TITLE = XpathString("//*[contains(@resource-id, 'id/editText')]")
SEARCH_BUTTON = XpathString("//*[contains(@resource-id, 'com.harman.ignite.appstore.audi:id/actionButtons')]")
SEARCH_NO_RESULTS = XpathString("//*[contains(@content-desc, 'shop_search_keyboard_no_results_list_item_nothing_found')]")
CLEAR_TEXT_BUTTON = XpathString("//*[contains(@resource-id, 'com.harman.ignite.appstore.audi:id/clearTextButton')]")
#SETTINGS_TITLE = XpathString("//*[contains(@text,'Settings')][contains(@resource-id, 'ignite.appstore.audi:id/titleTextViewRef')]")
SETTINGS_TITLE = XpathString("//*[contains(@text,'Settings')][contains(@resource-id, 'ignite.appstore.audi:id/titleTextViewRef')]")
SETTINGS_BUTTON = XpathString("//*[contains(@resource-id, 'com.harman.ignite.appstore.audi:id/menuActionsBackground')]")
KEYBOARD = XpathString("//*[contains(@resource-id, 'keyboard_wrapper')]")
CONFIRM_BUTTON = XpathString("//*[contains(@resource-id, 'android:id/button1')]")
CONTAINER_APP_LIST = XpathString("//*[contains(@resource-id, 'com.harman.ignite.appstore.audi:id/recyclerViewList')]")
ADD_BUTTON = XpathString("//*[@class='android.widget.Button' or @resource-id='com.harman.ignite.appstore.audi:id/operationPanelItemTextView'][contains(@text,'INSTALL') or contains(@text,'Install')]")
OPEN_BUTTON = XpathString("//*[@class='android.widget.Button' or @resource-id='com.harman.ignite.appstore.audi:id/operationPanelItemTextView'][contains(@text,'OPEN') or contains(@text,'Open')]")
CANCEL_BUTTON = XpathString("//*[@class='android.widget.Button' or @resource-id='com.harman.ignite.appstore.audi:id/operationPanelItemTextView'][contains(@text,'CANCEL') or contains(@text,'Cancel') or @resource-id='android:id/button2']")
REMOVE_BUTTON = XpathString("//*[@class='android.widget.Button' or @resource-id='com.harman.ignite.appstore.audi:id/operationPanelItemTextView'][contains(@text,'Uninstall')]")
UPDATE_BUTTON = XpathString("//*[@class='android.widget.Button' or @resource-id='com.harman.ignite.appstore.audi:id/operationPanelItemTextView'][contains(@text,'UPDATE') or contains(@text,'Update')]")
ADD_BUTTON_DISABLED = XpathString("//*[@class='android.widget.Button' or @resource-id='com.harman.ignite.appstore.audi:id/operationPanelItemTextView'][contains(@text,'INSTALL') or contains(@text,'Install')][@enabled='false']")
OPEN_BUTTON_DISABLED = XpathString("//*[@class='android.widget.Button' or @resource-id='com.harman.ignite.appstore.audi:id/operationPanelItemTextView'][contains(@text,'OPEN') or contains(@text,'Open')][@enabled='false']")
CANCEL_BUTTON_DISABLED = XpathString("//*[@class='android.widget.Button' or @resource-id='com.harman.ignite.appstore.audi:id/operationPanelItemTextView'][contains(@text,'CANCEL') or contains(@text,'Cancel') or @resource-id='android:id/button2'][@enabled='false']")
REMOVE_BUTTON_DISABLED = XpathString("//*[@class='android.widget.Button' or @resource-id='com.harman.ignite.appstore.audi:id/operationPanelItemTextView'][contains(@text,'Uninstall')][@enabled='false']")
UPDATE_BUTTON_DISABLED = XpathString("//*[@class='android.widget.Button' or @resource-id='com.harman.ignite.appstore.audi:id/operationPanelItemTextView'][contains(@text,'UPDATE') or contains(@text,'Update')][@enabled='false']")
CONTAINER_NOTIFICATION = XpathString("//*[contains(@resource-id, 'com.android.systemui:id/notifications')]")
SETTINGS_SEARCH_FIELD = XpathString("//*[contains(@resource-id, 'id/editText')]")
PRIVACY_MODE_TITLE = XpathString("//*[contains(@text,'Privacy')][contains(@resource-id,'com.harman.ignite.appstore.audi:id/operationPanelItemTextView')]")
LOADING_SPINNER = XpathString("//*[contains(@resource-id,'id/circularProgress') or contains(@resource-id,'loadingSpinner')]")
CIRCULAR_SPINNER = LOADING_SPINNER  # Hint: Double Xpath should be removed
POPUP_QUESTION = XpathString("//*[contains(@resource-id,'popupMessage')][contains(@text, 'want to') or contains(@text, 'like to')][@package='com.harman.ignite.appstore.audi']")
POPUP_AUTOMATIC_UPDATES = XpathString("//*[contains(@resource-id, 'popupTitle')][contains(@text, 'Automatic app updates')][@package='com.harman.ignite.appstore.audi']")
SUBTEXT = XpathString("//*[contains(@resource-id, 'listItemGrid2MainContent_textStart')][@text='{}']/../../..//*[contains(@resource-id, 'listItemGrid2MainContent_subtextStart')]")
SUBTEXT_GENERAL = XpathString("//*[contains(@resource-id,'subtext')]")
DETAIL_PAGE_ABOUT_THIS_APP_TITLE = XpathString("//*[contains(@content-desc,'shop_apps_detail_about_the_app_list_item_about_this_app') or contains(@content-desc,'shop_functions_detail_about_the_function_list_item_about_this_product')]")
DETAIL_PAGE_READ_MORE = XpathString("//*[contains(@content-desc,'details_read_more')]")
DETAIL_PAGE_WHATS_NEW = XpathString("//*[contains(@content-desc,'whats_new')]")
DISCLAIMER = XpathString("//*[contains(@resource-id,'com.harman.ignite.appstore.audi:id/disclaimer_text')]")
DIALOG_USER_MISSING = XpathString("//*[contains(@text,'Access is blocked. Please log in with your myAudi account.')]")
DIALOG_COMMUNICATION_ERROR = XpathString("//*[contains(@text,'Communication with the server is currently not possible. Please try again')]")
GENERIC_ERROR = XpathString("//*[contains(@content-desc,'error has occurred')][contains(@resource-id,'textView')]")
SYNC_BUTTON = XpathString("//*[contains(@text,'Try again')]")
CLICKABLE_LIST_ITEM = XpathString("//*[contains(@resource-id, 'textStart')]")
RECOMMENDATION_NAME = XpathString("//*[contains(@resource-id, 'com.harman.ignite.appstore.audi:id/appName')]")
TOOLBAR_TEXT = XpathString("//*[@class='android.widget.TextView'][@text='{}']")
LICENSE_PACKAGES_ENTRY = XpathString("//*[contains(@text, 'list of purchased license packages') or contains(@text,'list of purchased licence packages') or contains(@text,'ur Liste der gekauften Lizenzpakete')]")
NOT_IN_THIS_CAR_ENTRY = XpathString("//*[contains(@content-desc, 'string/shop_settings_not_installed_apps_toolbar_title')]")
DATA_PRIVACY_STATEMENT_ENTRY = XpathString("//*[contains(@content-desc, 'privacy')]")
IMPRINT_ENTRY = XpathString("//*[contains(@content-desc, 'imprint')]")
TERMS_OF_USE_ENTRY = XpathString("//*[contains(@content-desc, 'terms_of_use')]")
DISCLAIMER_ENTRY = XpathString("//*[contains(@content-desc, 'string/legal_settings_title_disclaimer')]")
COPYRIGHT_ENTRY = XpathString("//*[contains(@content-desc, 'string/legal_settings_title_copyright')]")
MEMORY_ENTRY = XpathString("//*[contains(@text,'Memory:') or contains(@text,'Storage:')]")
OPEN_SOURCE_LICENCES_ENTRY = XpathString("//*[contains(@resource-id,'listItemGrid2')][contains(@content-desc, 'open_source')]")
APP_VERSION_ENTRY = XpathString("//*[contains(@text,'App version')]")
SUPPLIER_COUNTRY_ENTRY = XpathString("//*[contains(@content-desc, 'supplier_country')]")
PURCHASE_BUTTON_VARIANT_SCREEN = XpathString("//*[contains(@content-desc, 'store_price_overview_viewmodel_button_desc')][@enabled='true']")
PURCHASE_BUTTON_FOD_SCREEN_TITLE = XpathString("//*[contains(@text,'heckout')][contains(@resource-id,'com.harman.ignite.appstore.audi:id/operationPanelItemTextView')]")
QR_CODE = XpathString("//*[contains(@resource-id,'com.harman.ignite.appstore.audi:id/qrcode')]")
LIST_ITEM = XpathString("//*[contains(@resource-id,'listItemGrid2MainContent_textStart')]")
LIST_ITEM_CATEGORY = XpathString("//*[contains(@resource-id,'text1')]")
BLOCKING_DISCLAIMER_TITLE = XpathString("//*[@resource-id='com.harman.ignite.appstore.audi:id/restrictions_info_group' or @resource-id='com.harman.ignite.appstore.audi:id/disclaimer_text']")
BLOCKING_DISCLAIMER_AUTOMATIC_UPDATES_TITLE = XpathString("//*[contains(@resource-id,'disclaimerText')][contains(@text,'For your safety, limited function while driving.')]")
LICENSE_IMAGE_SMALL = XpathString("//*[contains(@resource-id,'com.harman.ignite.appstore.audi:id/stepperDecoratorItem')]")
PREVIOUS_IMAGE_ARROW = XpathString("//*[contains(@content-desc,'drawable/ue_1302_stepper_decrement')]")
NEXT_IMAGE_ARROW = XpathString("//*[contains(@content-desc,'drawable/ue_1302_stepper_increment')]")
DIALOG_CLOSE_BUTTON = XpathString("//*[@class='android.widget.Button'][contains(@text,'OK') or contains(@text,'Cancel') or contains(@text,'Yes')]")
DIALOG_NOTCLOSE_BUTTON = XpathString("//*[@class='android.widget.Button'][contains(@text,'No')]")
SEARCH_CONTENT_ERROR = XpathString("//*[contains(@text,'Store content is not displayed')]")
SEARCH_THIRD_PARTY_MISSING = XpathString("//*[contains(@text,'Purchase the third-party store content license')]")
SEARCH_THIRD_PARTY_EXPIRED = XpathString("//*[contains(@text,'Renew the license for third-party store content')]")
NO_RESULTS = XpathString("//*[contains(@content-desc,'nothing_found')]")
GO_TO_TOP = XpathString("//*[contains(@content-desc,'LongTextDisclaimer-goToTopAction')]")
PRICE_INFO_PRODUCT_LIST = XpathString("//*[contains(@resource-id,'_textEnd')]")
OEM_LOGO_PRODUCT_LIST = XpathString("//*[contains(@resource-id,'com.harman.ignite.appstore.audi:id/contactImageView')]")
MAIN_CONTAINER = XpathString("//*[contains(@resource-id,'android:id/content')]")
BUTTON_BETA = XpathString("//*[contains(@text,'BETA')][@class='android.widget.RadioButton']")
BUTTON_STAGING = XpathString("//*[contains(@text,'STAGING')][@class='android.widget.RadioButton']")
BUTTON_PRODUCTION = XpathString("//*[contains(@text,'PRODUCTION')][@class='android.widget.RadioButton']")
ADD_BUTTON_OF_SPECIFIC_ELEMENT_IN_LIST = XpathString("//*[contains(@resource-id, 'com.harman.ignite.appstore.audi:id/recyclerViewList')]//*[@text='{}']/../../*//*[@class='android.widget.Button' or @resource-id='com.harman.ignite.appstore.audi:id/operationPanelItemTextView'][contains(@text,'INSTALL') or contains(@text,'Install')]")
OPEN_BUTTON_OF_SPECIFIC_ELEMENT_IN_LIST = XpathString("//*[contains(@resource-id, 'com.harman.ignite.appstore.audi:id/recyclerViewList')]//*[@text='{}']/../../*//*[@class='android.widget.Button' or @resource-id='com.harman.ignite.appstore.audi:id/operationPanelItemTextView'][contains(@text,'OPEN') or contains(@text,'Open')]")
CANCEL_BUTTON_OF_SPECIFIC_ELEMENT_IN_LIST = XpathString("//*[contains(@resource-id, 'com.harman.ignite.appstore.audi:id/recyclerViewList')]//*[@text='{}']/../../*//*[@class='android.widget.Button' or @resource-id='com.harman.ignite.appstore.audi:id/operationPanelItemTextView'][contains(@text,'CANCEL') or contains(@text,'Cancel') or @resource-id='android:id/button2']")
UPDATE_BUTTON_OF_SPECIFIC_ELEMENT_IN_LIST = XpathString("//*[contains(@resource-id, 'com.harman.ignite.appstore.audi:id/recyclerViewList')]//*[@text='{}']/../../*//*[@class='android.widget.Button' or @resource-id='com.harman.ignite.appstore.audi:id/operationPanelItemTextView'][contains(@text,'UPDATE') or contains(@text,'Update')][@enabled='false']")
PRIVACY_SETTINGS_BUTTON = XpathString("//*[contains(@text,'Privacy settings')]")
AUTOMATIC_UPDATES_TOGGLE_BUTTON_THIRD_PARTY = XpathString("//*[contains(@content-desc,'title_desc-switch')]")
AUTOMATIC_UPDATES_TOGGLE_BUTTON_GROUP_APP = XpathString("//*[contains(@content-desc,'without_subtext_desc-switch')]")
NOTIFICATION_HEADER = XpathString("//*[contains(@text,'Store')][contains(@resource-id,'com.android.systemui:id/header_app')]")
NOTIFICATION_SUBTEXT = XpathString("//*[contains(@text,'Store')]/../../..//*[contains(@resource-id,'com.android.systemui:id/notification_body_content')][contains(@text,'{}')]")
NOTIFICATION_SUBTEXT_OF_SPECIFIC_APP = XpathString("//*[@text='{}']/../*[@resource-id='com.android.systemui:id/notification_body_content']")  # Name of the app of which the subtext is needed, has to be formatted in.
NOTIFICATION_BUTTON = XpathString("//*[contains(@text,'Store')]/../../..//*[contains(@text,'{}')]")
NOTIFICATION_GROUP_TOGGLE = XpathString("//*[contains(@text,'Store')]/../..//*[contains(@resource-id,'com.android.systemui:id/group_toggle_icon')]")
PURCHASE_INFORMATION_MAIN_TEXT_VIEW = XpathString("//*[contains(@resource-id,'mainTextView')]")
BILLING_ADDRESS_DESC = XpathString("//*[contains(@resource-id,'id/billing_address_desc')]")
PAYMENT_METHOD = XpathString("//*[contains(@resource-id,'id/payment_method')]")
PAYMENT_DETAILS = XpathString("//*[contains(@resource-id,'id/payment_details')]")
BILLINGADRESS_DETAILS = XpathString("//*[contains(@resource-id,'id/billing_address_details')]")
PURCHASECONFIRMATION_TEXT = XpathString("//*[contains(@resource-id,'com.harman.ignite.appstore.audi:id/order_creation_text')]")
COMPLETE_PURCHASE_BUTTON = XpathString("//*[contains(@text,'Buy')]")
CANCELLATION_BUTTON = XpathString("//*[contains(@text,'Cancellation')]")
CONTINUE_BUTTON = XpathString("//*[contains(@text,'Continue')]")
OK_BUTTON = XpathString("//*[contains(@text,'OK')]")
TERMSOFUSE_BUTTON = XpathString("//*[contains(@text,'Terms of use')]")
DIALOG_OPTION_CANCEL = XpathString("//*[contains(@resource-id,'android:id/button3')]")
DIALOG_OPTION_INTHECAR = XpathString("//*[contains(@resource-id,'android:id/button2')]")
DIALOG_OPTION_MYAUDIAPP = XpathString("//*[contains(@resource-id,'android:id/button1')]")
ORDERCREATION = XpathString("//*[contains(@content-desc,'string/order_creation_in_process')]")
CHECKOUT_DIALOG_TERMS_OF_USE_LINK = XpathString("//*[contains(@content-desc,'string/shop_legal_list_item_title_terms_of_use')]")
CHECKOUT_DIALOG_RIGHT_OF_WITHDRAWAL_LINK = XpathString("//*[contains(@content-desc,'string/button_cancellation')]")
CHECKBOX_ACCEPT_TERMS = XpathString("//*[contains(@content-desc,'shop_functions_detail_deep_checkout_complete_process_checkbox_accept_terms_text')]")
CHECKBOX_ACCEPT_TERMS_NOTCHECKED = XpathString("//*[contains(@content-desc,'shop_functions_detail_deep_checkout_complete_process_checkbox_accept_terms_text')][@checked='false']")
CHECKBOX_ACCEPT_TERMS_CHECKED = XpathString("//*[contains(@content-desc,'shop_functions_detail_deep_checkout_complete_process_checkbox_accept_terms_text')][@checked='true']")
DIALOG_BUTTON_OK = XpathString("//*[contains(@text,'OK') or contains(@text,'Yes') or contains(@text,'Confirm')]")
CONTENT_DETAIL_PAGE = XpathString("//*[contains(@resource-id,'com.harman.ignite.appstore.audi:id/content_tv')]")
WEB_VIEW = XpathString("//*[@class='android.webkit.WebView']")
THIRD_PARTY_LEGAL_INFO_CONTENT = XpathString("//*[contains(@resource-id,'com.harman.ignite.appstore.audi:id/legal_info_list')]")
THIRD_PARTY_LEGAL_ENTRY = XpathString("//*[contains(@text,'Legal')]")
THIRD_PARTY_TERMS_OF_USE_ENTRY = XpathString("//*[contains(@text,'Terms of')]")
THIRD_PARTY_IMPRINT_ENTRY = XpathString("//*[contains(@text,'Privacy')]")
THIRD_PARTY_OPEN_SOURCE_ENTRY = XpathString("//*[contains(@text,'Open Source')]")
THIRD_PARTY_RIGHT_TO_WITHDRAWAL_ENTRY = XpathString("//*[contains(@text,'Right to')]")
SKELETON_TITLE = XpathString("//*[contains(@resource-id,'com.harman.ignite.appstore.audi:id/skeleton_screen_layout')]")
DISCLAIMER_CHANGE_SETTINGS_TITLE = XpathString("//*[contains(@text,'Change settings')]")
SELECTED_COUNTRY_RADIO_BUTTON = XpathString("//*[contains(@resource-id,'id/radioButton')][@checked='true']")
SELECTED_COUNTRY_RADIO_BUTTON_TEXT = XpathString("//*[contains(@resource-id,'id/radioButton')][@checked='true']/../..//*[contains(@resource-id,'textStart')]/@text")
DISCLAIMER_CLOSE_BUTTON = XpathString("//*[contains(@resource-id,'com.harman.ignite.appstore.audi:id/popupCloseButton')]")
AUTOMATIC_UPDATES_INFO_THIRD_PARTY = XpathString("//*[contains(@content-desc, 'store_settings_viewmodel_title_desc')]//*[@class='android.widget.ImageButton']")
AUTOMATIC_UPDATES_POP_UP_THIRD_PARTY = XpathString("//*[contains(@resource-id,'popupTitle')][contains(@text,'party apps')]")
AUTOMATIC_UPDATES_INFO_GROUP_APPS = XpathString("//*[contains(@content-desc, 'store_settings_viewmodel_title_without_subtext_desc')]//*[@class='android.widget.ImageButton']")
AUTOMATIC_UPDATES_POP_UP_GROUP_APPS = XpathString("//*[contains(@resource-id,'popupTitle')][contains(@text,'Audi apps')]")
INSTALLATION_POPUP_CHECKBOX = XpathString("//*[contains(@resource-id,'com.harman.ignite.appstore.audi:id/popupCheckbox')]")
INSTALLATION_POPUP_CHECKBOX_CHECKED = XpathString("//*[@resource-id='com.harman.ignite.appstore.audi:id/popupCheckbox'][@checked='true']")
INSTALLATION_POPUP_TEXT = XpathString("//*[contains(@text,'may incur costs')]")
SEARCH_CATEGORY_NOT_INSTALLED_APPS = XpathString("//*[contains(@content-desc,':string/shop_apps_tab_layout_explore_tab_label')]")
SEARCH_CATEGORY_INSTALLED_APPS = XpathString("//*[contains(@content-desc,'string/shop_search_keyboard_closed_list_item_header_category_3rd_party_installed')]")
SEARCH_CATEGORY_FOD = XpathString("//*[contains(@content-desc,'string/shop_search_keyboard_closed_list_item_header_category_acp_installed')]")
SHOP_FUNCTIONS_PRICE_INFORMATION_LIST_ELEMENT = XpathString("//*[contains(@resource-id,'listItemGrid2MainContent_textStart')][contains(@text,'Price information')]")
PRICE_INFORMATION = XpathString("//*[contains(@resource-id,'titleTextViewRef')][contains(@text,'Price information')]")
IMPRINT_TAB1 = XpathString("//*[contains(@resource-id,'listItemGrid2MainContent_textStart')][contains(@content-desc,'title_imprint')]")
PRIVACY_POLICY_TAB1 = XpathString("//*[contains(@resource-id,'textStart')][contains(@content-desc,'privacy_policy')]")
TERMS_OF_USE_TAB1 = XpathString("//*[contains(@resource-id,'columnTextStart')]//*[contains(@content-desc,'terms_of_use')]")
PRIVACY_RIGHT_OF_WITHDRAWAL_TAB1 = XpathString("//*[contains(@text, 'Right of withdrawal')]")
IMPRINT = XpathString("//*[contains(@resource-id,'titleArea')]//*[contains(@content-desc,'Imprint') or contains(@text,'Impressum')]")
IMPRINT_AND_LEGAL_DOCUMENTS = XpathString("//*[contains(@text,'legal information')][contains(@resource-id,'TextView')]")
DATA_PRIVACY = XpathString("//*[contains(@resource-id,'titleArea')]//*[contains(@text,'Privacy policy') or contains(@text,'Datenschutzhinweis')]")
TAB1_LEGAL_CATEGORY = XpathString("//*[contains(@text,'PRIVACY') and contains(@text,'PRICE INFORMATION')][contains(@resource-id,'id/text1')]")
AUTOMATIC_UPDATES_LIST_ITEM_THIRY_PARTY = XpathString("//*[contains(@content-desc, 'store_settings_viewmodel_title_desc')]")
IGNITE_VARIANT_SELECTION_TEXT = XpathString("//*[contains(@resource-id,'textStart')][contains(@text,'product version')]")
LIST_ITEM_GLOBAL_SEARCH = XpathString("//*[@resource-id='de.eso.globalsearch:id/text1']")
GENERIC_SEARCH_HINT = XpathString("//*[contains(@resource-id, 'id/editText')][contains(@text,'{}')]")  # Name of the text in the search hint needs to be formatted in.
GENERIC_LIST_ITEM = XpathString("//*[contains(@resource-id, 'com.harman.ignite.appstore.audi:id/recyclerViewList')]//*[contains(@text,'{}')]")  # List item with text which needs to be formatted in.
PRODUCT_AUDI_LOGBOOK_ONLINE_CLICK_ELEMENT = XpathString("//*[contains(@text,'Audi Logbook Online')]")
USAGE_INSTRUCTIONS_DETAIL_PAGE = XpathString("//*[contains(@content-desc,'shop_functions_detail_list_item_usage_instructions_title')]")
ABOUT_THIS_FUNCTION = XpathString("//*[contains(@content-desc,'shop_functions_detail_about_the_function_list_item_about_this_product')]")
DETAIL_PAGE_OPERATION_PANEL = XpathString("//*[contains(@resource-id,'id/operation_panel')]")
INTRODUCTURY_ICON = XpathString("//*[contains(@resource-id,'id/picture_in_left_big_window')]")
BOUGHT_PRODUCT_NAME = XpathString("//*[contains(@resource-id,'id/productName')]")
BOUGHT_PRODUCT_LICENSE_RUN_TIME = XpathString("(//*[contains(@resource-id,'id/licenseRunTime')])[2]")
BOUGHT_PRODUCT_LOGO = XpathString("//*[contains(@resource-id,'id/providerLogoStartImageView')]")
CANCEL_DIALOG_PUCHASE = XpathString("//*[contains(@resource-id,'popupMessage')][contains(@text,'cancel the purchase')]")
ICON_THIRD_PARTY_APP = XpathString("//*[contains(@resource-id,'contactImageView')]")
APP_LIST_GLOBAL_SEARCH = XpathString("//*[contains(@resource-id,'listItemGrid2MainContent_textStart')]")
PURCHASABLE_VARIANTS_PRICE_INFORMATION_LIST_ITEM = XpathString("//*[contains(@text,'Price information')]")
APP_DETAIL_PAGE_ABOUT_THIS_APP_SUBTEXT = XpathString("//*[contains(@text,'Seller') or contains(@text,'Provider')]")
FOD_ABOUT_THIS_APP_SUBTEXT = XpathString("//*[contains(@resource-id,'id/listItemGrid2MainContent_subtextStart')]")
DEEP_CHECKOUT_LEGAL_LIST_HEADLINE = XpathString("//*[@class='android.widget.TextView'][contains(@text,'Legal notes') or contains(@text,'Legal')]")
MY_APPLICATIONS_CATEGORY_UPDATES = XpathString("//*[@class='android.widget.TextView'][contains(@text,'Updates')]")
MY_APPLICATIONS_CATEGORY_UPDATE_HISTORY = XpathString("//*[@class='android.widget.TextView'][contains(@text,'HISTORY')]")
MY_APPLICATIONS_CATEGORY_FUNCTIONS_DEMAND = XpathString("//*[@class='android.widget.TextView'][contains(@text,'FUNCTIONS')]")
POPUP_WELCOME_HEADLINE = XpathString("//*[contains(@text, 'Country') or contains(@text, 'Welcome')][contains(@resource-id, 'popupTitle')][@package='com.harman.ignite.appstore.audi']")
DETAIL_PAGE_ABOUT_THIS_APP_HEADLINE = XpathString("//*[@class='android.widget.TextView'][contains(@text,'About this app')]")
DETAIL_PAGE_READ_MORE_HEADLINE = XpathString("//*[contains(@resource-id,'developer_info_list')]")
DETAIL_PAGE_WHATS_NEW_HEADLINE = XpathString("//*[@class='android.widget.TextView'][contains(@text,'What') and contains(@text,'s new')]")
SUPPLIER_COUNTRY_HEADLINE = XpathString("//*[contains(@resource-id,'countries_list')]")
LICENSE_PACKAGES_HEADLINE = XpathString("//*[contains(@resource-id,'titleTextViewRef')][contains(@text,'License packages') or contains(@text,'Licence packages')]")
LICENSE_IMAGE_LARGE_HEADLINE = XpathString("//*[@class='android.widget.TextView'][contains(@text,'Pictures and videos') or contains(@text,'Graphics and videos')]")
OPEN_SOURCE_HEADLINE = XpathString("//*[contains(@resource-id,'titleText')][contains(@text,'Open Source Software Notice')]")
PURCHASE_INFORMATION_HEADLINE = XpathString("//*[contains(@resource-id,'titleText')][contains(@text,'Purchase information')]")
SHOPPING_CART_HEADLINE = XpathString("//*[contains(@resource-id,'titleText')][contains(@text,'Shopping cart') or contains(@text,'Basket')]")
BILLING_INFORMATION_HEADLINE = XpathString("//*[contains(@resource-id,'titleText')][contains(@text,'Billing information')]")
CHECKOUT_DIALOG_HEADLINE = XpathString("//*[contains(@resource-id,'popupMessage')][contains(@text,'PayPal') or contains(@text,'checkout option')]")
PURCHASECONFIRMATION_HEADLINE = XpathString("//*[contains(@resource-id,'titleText')][contains(@text,'confirmation')]")
TERMS_OF_USE_HEADLINE = XpathString("//*[contains(@resource-id,'titleText')][contains(@text,'Terms of use')]")
PRIVACY_POLICY_HEADLINE = XpathString("//*[contains(@resource-id,'titleText')][contains(@text,'Privacy policy')]")
INCLUDED_APPS_HEADLINE = XpathString("//*[contains(@resource-id,'titleText')][contains(@text,'Included Apps')]")
USAGE_INSTRUCTIONS_HEADLINE = XpathString("//*[contains(@resource-id,'titleText')][contains(@text,'Usage information') or contains(@text,'Terms of use')]")
COUNTRY_SELECTION_DISCLAIMER_HEADLINE_TITLE = XpathString("//*[contains(@text,'Country offering store') or contains(@text,'Welcome')][contains(@resource-id,'popupTitle')]")
FULLSCREEN_POPUP_WELCOME = POPUP_WELCOME_HEADLINE
GENERIC_HEADLINE = XpathString("//*[contains(@resource-id,'titleTextViewRef')][contains(@text,'{}')]")  # Name of the headline needs to be formatted in.
RIGHT_OF_WITHDRAWAL_HEADLINE = XpathString("//*[contains(@resource-id,'titleArea')]//*[contains(@text,'Legal notes') or contains(@text,'Legal')]")
DETAIL_PAGE_ABOUT_THIS_FUNCTION_HEADLINE = XpathString("//*[contains(@text,'About this product')]")
PRICE_INFORMATION_HEADLINE = XpathString("//*[contains(@resource-id,'titleArea')]//*[contains(@text,'Price information')]")
LEGAL_INFORMATION_HEADLINE = DEEP_CHECKOUT_LEGAL_LIST_HEADLINE
NOT_IN_THIS_CAR_TITLE = XpathString("//*[contains(@text,'Apps not')][@class='android.widget.TextView']")
POPUP_TITLE_INSTALLATION = XpathString("//*[contains(@resource-id,'popupTitle')][@package='com.harman.ignite.appstore.audi']")
NOTE_TITLE = XpathString("//*[contains(@text,'Store: Notes')]")
VARIANT_SELECTION_TITLE = XpathString("//*[contains(@resource-id,'titleText')][contains(@text,'available to buy') or contains(@text,'available for')]")
TITLE_LINE = XpathString("//*[@class='android.widget.TextView'][@package='com.harman.ignite.appstore.audi']")
NOTIFICATION_TITLE = XpathString(NAME.get() + "/../../..//*[contains(@resource-id,'com.android.systemui:id/notification_body_title')][contains(@text,'{}')]")
TEST = XpathString("//*[contains(@resource-id,'com.android.systemui:id/notification_body_title')][@text='{}']")
