# -*- coding: utf-8 -*-
"""Module contains xpath of radio app."""
import enna_hcp_configuration.android.xpaths
from . import XpathString

# pylint: disable = no-name-in-module, line-too-long
if enna_hcp_configuration.android.xpaths.CLUSTER == enna_hcp_configuration.android.xpaths.SupportedClusters.CLU55:
	from enna_hcp_configuration.texts.CLU55.center.de.eso.radio import bl as radio
elif enna_hcp_configuration.android.xpaths.CLUSTER == enna_hcp_configuration.android.xpaths.SupportedClusters.CLU53:
	from enna_hcp_configuration.texts.CLU53.center.de.eso.radio import bl as radio
elif enna_hcp_configuration.android.xpaths.CLUSTER == enna_hcp_configuration.android.xpaths.SupportedClusters.CLU51:
	from enna_hcp_configuration.texts.CLU51.center.de.eso.radio import bl as radio
elif enna_hcp_configuration.android.xpaths.CLUSTER == enna_hcp_configuration.android.xpaths.SupportedClusters.CLU48:
	from enna_hcp_configuration.texts.CLU48.center.de.eso.radio import bl as radio
else:
	from enna_hcp_configuration.texts.CLU46.center.de.eso.radio import bl as radio

CHANGESOURCE_BUTTON = XpathString("//*[contains(@content-desc, 'actionChangeSource')]")
INIT_TITLE = XpathString("//*[@resource-id='de.eso.radio:id/initTextView']")
LIST_CONTAINER = XpathString("//*[@class='androidx.recyclerview.widget.RecyclerView']")
MAIN_AM_BUTTON = XpathString("//*[@index='3'][@class='android.widget.LinearLayout' or @class='androidx.appcompat.app.ActionBar$Tab'][@package='de.eso.radio'][@clickable='true'][@selected='false']")
MAIN_AM_SELECTED_TITLE = XpathString("//*[@index='3'][@class='android.widget.LinearLayout' or @class='androidx.appcompat.app.ActionBar$Tab'][@package='de.eso.radio'][@focusable='true'][@selected='true']")
MAIN_DAB_FM_BUTTON = XpathString("//*[@index='2'][@class='android.widget.LinearLayout' or @class='androidx.appcompat.app.ActionBar$Tab'][@package='de.eso.radio'][@clickable='true'][@selected='false']")
MAIN_DAB_FM_SELECTED_TITLE = XpathString("//*[@index='2'][@class='android.widget.LinearLayout' or @class='androidx.appcompat.app.ActionBar$Tab'][@package='de.eso.radio'][@focusable='true'][@selected='true']")
MAIN_FAVORITES_BUTTON = XpathString("//*[@index='1'][@class='android.widget.LinearLayout' or @class='androidx.appcompat.app.ActionBar$Tab'][@package='de.eso.radio'][@clickable='true'][@selected='false']")
MAIN_FAVORITES_SELECTED_TITLE = XpathString("//*[@index='1'][@class='android.widget.LinearLayout' or @class='androidx.appcompat.app.ActionBar$Tab'][@package='de.eso.radio'][@focusable='true'][@selected='true']")
MAIN_LAST_STATIONS_BUTTON = XpathString("//*[@index='0'][@class='android.widget.LinearLayout' or @class='androidx.appcompat.app.ActionBar$Tab'][@package='de.eso.radio'][@clickable='true'][@selected='false']")
MAIN_LAST_STATIONS_SELECTED_TITLE = XpathString("//*[@index='0'][@class='android.widget.LinearLayout' or @class='androidx.appcompat.app.ActionBar$Tab'][@package='de.eso.radio'][@focusable='true'][@selected='true']")
MAIN_MINI_PLAYER = XpathString("//*[@resource-id='miniPlayerTouchArea'][@class='android.view.View']")
NOW_PLAYING_MINIMIZE = XpathString("//*[contains(@content-desc, 'actionClosePlayer') or contains(@resource-id, 'titleLineActionClosePlayer') or contains(@resource-id, 'ActionClosePlayer')]")
NOW_PLAYING_TITLE = XpathString(f"//*{radio.radio_queue_title___last_stations_list}")
SEARCH_BAR_TITLE = XpathString("//*[contains(@content-desc, 'de.eso.radio:string/search_input_hint')]")
SEARCH_BUTTON = XpathString("//*[contains(@content-desc, 'actionSearch')]")
SEARCH_CLOSE_BUTTON = XpathString("//*[contains(@content-desc, 'actionBack')]")
SETTINGS_BRG_TITLE = XpathString("//*[contains(@content-desc, 'de.eso.radio:string/radio_settings_broadcast_radio_gem_title')]")
SETTINGS_BROADCAST_RADIO_GEM = XpathString("//*[contains(@content-desc, 'de.eso.radio:string/radio_settings_broadcast_radio_gem')]")
SETTINGS_BUTTON = XpathString("//*[contains(@content-desc, 'actionSettings') or contains(@resource-id, 'de.eso.radio:id/titleLineActionSettings')]")
SETTINGS_LIST = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']")
SETTINGS_PROVIDER_INFO_BUTTON = XpathString(f"//*{radio.radio_settings_provider_info}")
SETTINGS_PROVIDER_INFO_TITLE = XpathString(f"//*[@resource-id='de.eso.radio:id/titleTextViewRef']{radio.radio_settings_provider_info_title}")
SETTINGS_OSD_BUTTON = XpathString(f"//*{radio.radio_settings_open_source_disclaimer}")
SETTINGS_OSD_TITLE = XpathString(f"//*[@resource-id='de.eso.radio:id/titleTextViewRef']{radio.radio_settings_open_source_disclaimer_title}")
SETTINGS_CUSTOM_BL_GEMS_BUTTON = XpathString("//*[contains(@content-desc, 'de.eso.radio:string/radio_custom_gem_chooser')]")
SETTINGS_CUSTOM_BL_GEMS_TITLE = XpathString("//*[contains(@content-desc,'de.eso.radio:string/radio_custom_gem_chooser_headline')]")
SETTINGS_CUSTOM_BL_GEMS_LIST = XpathString("//*[@resource-id='gem_entries_list']")
SETTINGS_CUSTOM_BL_GEMS_GENERAL_BUTTON = XpathString("//*[contains(@text,'> GENERAL')]")
SETTINGS_CUSTOM_BL_GEMS_GENERAL_TITLE = XpathString("//*[contains(@text,'GEM for GENERAL')][@resource-id='de.eso.radio:id/titleTextViewRef']")
SETTINGS_CUSTOM_BL_GEMS_GENERAL_CODING_SIMULATION_MODE = XpathString("//*[contains(@text,'Coding Simulation Mode [ ')]")
SETTINGS_CUSTOM_BL_GEMS_GENERAL_CODING_SIMULATION_MODE_PREVIOUS_BUTTON = XpathString(f"{SETTINGS_CUSTOM_BL_GEMS_LIST}/*[@index=10]")
SETTINGS_CUSTOM_BL_GEMS_GENERAL_CODING_SIMULATION_MODE_NEXT_BUTTON = XpathString(f"{SETTINGS_CUSTOM_BL_GEMS_LIST}/*[@index=11]")
SETTINGS_CUSTOM_BL_GEMS_GENERAL_CODING_SIMULATION_TRIGGER_RESTART_BUTTON = XpathString(f"{SETTINGS_CUSTOM_BL_GEMS_LIST}/*[@text='[ Trigger restart of app ]']")
SETTINGS_CUSTOM_BL_GEMS_GENERAL_RADIOMANAGER_SIMULATION_MODE = XpathString("//*[contains(@text,'RadioManager Simulation Mode [ ')]")
SETTINGS_CUSTOM_BL_GEMS_GENERAL_RADIOMANAGER_SIMULATION_MODE_PREVIOUS_BUTTON = XpathString(f"{SETTINGS_CUSTOM_BL_GEMS_LIST}/*[@index=14]")
SETTINGS_CUSTOM_BL_GEMS_GENERAL_RADIOMANAGER_SIMULATION_MODE_NEXT_BUTTON = XpathString(f"{SETTINGS_CUSTOM_BL_GEMS_LIST}/*[@index=15]")
SETTINGS_CUSTOM_BL_GEMS_DOMAIN_ANNOUNCEMENT_BUTTON = XpathString("//*[contains(@text,'DOMAIN_ANNOUNCEMENT')]")
SETTINGS_CUSTOM_BL_GEMS_DOMAIN_ANNOUNCEMENT_TITLE = XpathString("//*[contains(@text,'GEM for DOMAIN_ANNOUNCEMENT')][@resource-id='de.eso.radio:id/titleTextViewRef']")
SETTINGS_CUSTOM_BL_GEMS_DOMAIN_ANNOUNCEMENT_TYPE = XpathString("//*[contains(@text,'Type [ ')]")
SETTINGS_CUSTOM_BL_GEMS_DOMAIN_ANNOUNCEMENT_TYPE_PREVIOUS_BUTTON = XpathString(f"{SETTINGS_CUSTOM_BL_GEMS_LIST}/*[@index=14]")
SETTINGS_CUSTOM_BL_GEMS_DOMAIN_ANNOUNCEMENT_TYPE_NEXT_BUTTON = XpathString(f"{SETTINGS_CUSTOM_BL_GEMS_LIST}/*[@index=15]")
SETTINGS_CUSTOM_BL_GEMS_DOMAIN_ANNOUNCEMENT_ACTIVE_BUTTON = XpathString("//*[contains(@text,'Active [')]")

BROWSER_FAVORITES_EMPTY_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/browser_no_favorite_saved_yet']")
BROWSER_LAST_STATIONS_EMPTY_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/browser_no_last_stations_available']")
BROWSER_STATION_LIST_INDEX_0_ITEM = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='0']")
BROWSER_STATION_LIST_INDEX_0_STATION_LOGO = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='0']//*[@resource-id='de.eso.radio:id/coverImage']")
BROWSER_STATION_LIST_INDEX_0_STATION_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='0']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
BROWSER_STATION_LIST_INDEX_0_GENRE_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='0']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
BROWSER_STATION_LIST_INDEX_0_RECEPTION_ICON = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='0']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
BROWSER_STATION_LIST_INDEX_0_FAVORITE_ICON = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='0']//*[@resource-id='de.eso.radio:id/listItemButton_0']")
BROWSER_STATION_LIST_INDEX_1_ITEM = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='1']")
BROWSER_STATION_LIST_INDEX_1_STATION_LOGO = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='1']//*[@resource-id='de.eso.radio:id/coverImage']")
BROWSER_STATION_LIST_INDEX_1_STATION_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='1']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
BROWSER_STATION_LIST_INDEX_1_GENRE_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='1']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
BROWSER_STATION_LIST_INDEX_1_RECEPTION_ICON = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='1']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
BROWSER_STATION_LIST_INDEX_1_FAVORITE_ICON = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='1']//*[@resource-id='de.eso.radio:id/listItemButton_0']")
BROWSER_STATION_LIST_INDEX_2_ITEM = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='2']")
BROWSER_STATION_LIST_INDEX_2_STATION_LOGO = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='2']//*[@resource-id='de.eso.radio:id/coverImage']")
BROWSER_STATION_LIST_INDEX_2_STATION_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='2']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
BROWSER_STATION_LIST_INDEX_2_GENRE_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='2']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
BROWSER_STATION_LIST_INDEX_2_RECEPTION_ICON = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='2']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
BROWSER_STATION_LIST_INDEX_2_FAVORITE_ICON = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='2']//*[@resource-id='de.eso.radio:id/listItemButton_0']")
BROWSER_STATION_LIST_INDEX_3_ITEM = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='3']")
BROWSER_STATION_LIST_INDEX_3_STATION_LOGO = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='3']//*[@resource-id='de.eso.radio:id/coverImage']")
BROWSER_STATION_LIST_INDEX_3_STATION_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='3']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
BROWSER_STATION_LIST_INDEX_3_GENRE_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='3']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
BROWSER_STATION_LIST_INDEX_3_RECEPTION_ICON = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='3']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
BROWSER_STATION_LIST_INDEX_3_FAVORITE_ICON = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='3']//*[@resource-id='de.eso.radio:id/listItemButton_0']")
BROWSER_STATION_LIST_INDEX_4_ITEM = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='4']")
BROWSER_STATION_LIST_INDEX_4_STATION_LOGO = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='4']//*[@resource-id='de.eso.radio:id/coverImage']")
BROWSER_STATION_LIST_INDEX_4_STATION_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='4']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
BROWSER_STATION_LIST_INDEX_4_GENRE_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='4']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
BROWSER_STATION_LIST_INDEX_4_RECEPTION_ICON = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='4']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
BROWSER_STATION_LIST_INDEX_4_FAVORITE_ICON = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='4']//*[@resource-id='de.eso.radio:id/listItemButton_0']")
BROWSER_STATION_LIST_INDEX_5_ITEM = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='5']")
BROWSER_STATION_LIST_INDEX_5_STATION_LOGO = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='5']//*[@resource-id='de.eso.radio:id/coverImage']")
BROWSER_STATION_LIST_INDEX_5_STATION_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='5']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
BROWSER_STATION_LIST_INDEX_5_GENRE_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='5']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
BROWSER_STATION_LIST_INDEX_5_RECEPTION_ICON = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='5']//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
BROWSER_STATION_LIST_INDEX_5_FAVORITE_ICON = XpathString("//*[@resource-id='de.eso.radio:id/recyclerViewList']/*[@class='android.widget.FrameLayout' and @index='5']//*[@resource-id='de.eso.radio:id/listItemButton_0']")

NOTIFICATION = XpathString("//*[@resource-id='com.android.systemui:id/notification_headsup']")
NOTIFICATION_APP_ICON = XpathString("//*[@resource-id='com.android.systemui:id/notification_headsup']//*[@resource-id='com.android.systemui:id/app_icon']")
NOTIFICATION_APP_TEXT = XpathString("//*[@resource-id='com.android.systemui:id/notification_headsup']//*[@resource-id='com.android.systemui:id/header_text']")
NOTIFICATION_BODY_TITLE_TEXT = XpathString("//*[@resource-id='com.android.systemui:id/notification_headsup']//*[@resource-id='com.android.systemui:id/notification_body_title']")
NOTIFICATION_BODY_CONTENT_TEXT = XpathString("//*[@resource-id='com.android.systemui:id/notification_headsup']//*[@resource-id='com.android.systemui:id/notification_body_content']")
NOTIFICATION_BUTTON_LEFT = XpathString("//*[@resource-id='com.android.systemui:id/notification_headsup']//*[@resource-id='com.android.systemui:id/notification_action_button1']")
NOTIFICATION_BUTTON_LEFT_TEXT = XpathString("//*[@resource-id='com.android.systemui:id/notification_headsup']//*[@resource-id='com.android.systemui:id/notification_action_button1']//*[@class='android.widget.TextView']")
NOTIFICATION_BUTTON_RIGHT = XpathString("//*[@resource-id='com.android.systemui:id/notification_headsup']//*[@resource-id='com.android.systemui:id/notification_action_button2']")
NOTIFICATION_BUTTON_RIGHT_TEXT = XpathString("//*[@resource-id='com.android.systemui:id/notification_headsup']//*[@resource-id='com.android.systemui:id/notification_action_button2']//*[@class='android.widget.TextView']")

MAIN_TABBAR_DAB_FM_TEXT = XpathString("//*[@index='2'][contains(@content-desc, 'DAB/FM')]/.//*[@class='android.widget.TextView']")
MAIN_TABBAR_DAB_FM_ICON = XpathString("//*[@index='2'][contains(@content-desc, 'DAB/FM')]/.//*[@class='android.widget.ImageView']")
MAIN_TABBAR_FAVORITES_TEXT = XpathString("//*[@index='1'][contains(@content-desc, 'Favoriten')]/.//*[@class='android.widget.TextView']")
MAIN_TABBAR_FAVORITES_ICON = XpathString("//*[@index='1'][contains(@content-desc, 'Favoriten')]/.//*[@class='android.widget.ImageView']")
MAIN_TABBAR_LAST_STATIONS_TEXT = XpathString("//*[@index='0'][contains(@content-desc, 'Letzte Sender')]/.//*[@class='android.widget.TextView']")
MAIN_TABBAR_LAST_STATIONS_ICON = XpathString("//*[@index='0'][contains(@content-desc, 'Letzte Sender')]/.//*[@class='android.widget.ImageView']")

MORE_MENUE_DELETE_BUTTON = XpathString("//*[@content-desc='###ctxMenuItemDelete']")
MORE_MENUE_DELETE_ALL_BUTTON = XpathString("//*[@content-desc='###ctxMenuItemDeleteAll']")
MORE_MENUE_TOGGLE_FAVORITE_BUTTON = XpathString("//*[@content-desc='###ctxMenuItemToggleFavorite']")
MINIPLAYER = XpathString("//*[@resource-id='de.eso.radio:id/miniPlayerComposeView']//*[@content-desc='stationLogoBlur']")
MINIPLAYER_OPERATION_PANEL = XpathString("//*[@package='de.eso.radio']//*[@resource-id='de.eso.radio:id/miniPlayer']")
MINIPLAYER_PLAY_PAUSE_BUTTON = XpathString("//*[@resource-id='de.eso.radio:id/miniplayerControlsBtnPlayPause']")
MINIPLAYER_PLAY_PAUSE_BUTTON_MUTE_ACTIVE = XpathString("//*[@resource-id='de.eso.radio:id/miniplayerControlsBtnPlayPause']//*[@content-desc='###de.eso.radio:drawable/mute_active']")
MINIPLAYER_PLAY_PAUSE_BUTTON_MUTE_INACTIVE = XpathString("//*[@resource-id='de.eso.radio:id/miniplayerControlsBtnPlayPause']//*[@content-desc='###de.eso.radio:drawable/mute_inactive']")
MINIPLAYER_STATION_LOGO = XpathString("//*[@resource-id='de.eso.radio:id/miniPlayerComposeView']//*[@resource-id='stationLogo']")
MINIPLAYER_STATION_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/miniPlayerComposeView']//*[@resource-id='miniPlayerMainInfo']")
MINIPLAYER_SKIP_BW_BUTTON = XpathString("//*[@resource-id='de.eso.radio:id/miniplayerControlsBtnSkipPrevious']")
MINIPLAYER_SKIP_BW_BUTTON_ICON = XpathString("//*[@resource-id='de.eso.radio:id/miniplayerControlsBtnSkipPrevious']//*[@content-desc='###de.eso.radio:drawable/e82d_media_skip_backward']")
MINIPLAYER_SKIP_FW_BUTTON = XpathString("//*[@resource-id='de.eso.radio:id/miniplayerControlsBtnSkipNext']")
MINIPLAYER_SKIP_FW_BUTTON_ICON = XpathString("//*[@resource-id='de.eso.radio:id/miniplayerControlsBtnSkipNext']//*[@content-desc='###de.eso.radio:drawable/e82c_media_skip_forward']")
NOW_PLAYING_TABBAR_CLOSE_BUTTON = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@resource-id='de.eso.radio:id/titleLineActionClosePlayer']")
NOW_PLAYING_TABBAR_SOURCE_BUTTON = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@resource-id='de.eso.radio:id/titleLineActionChangeSource']")
NOW_PLAYING_TABBAR_TITLE_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@resource-id='de.eso.radio:id/titleTextViewRef']")
NOW_PLAYING_TABBAR_RT_HISTORY_BUTTON = XpathString("//*[@resource-id='de.eso.radio:id/titleLineMenuActionOpenRTHistory']")
NOW_PLAYING_GLASPLATE = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']//*[@content-desc='stationLogoBlur']")
NOW_PLAYING_STATION_LOGO = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']//*[@resource-id='stationLogo']")
NOW_PLAYING_SOURCE_TYPE_ICON = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']//*[@resource-id='sourceTypeIcon']")
NOW_PLAYING_HYBRID_LINKING_INDICATOR_ICON = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']//*[@content-desc='hybridLinkingIndicatorIcon']")
NOW_PLAYING_WEB_ICON = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']//*[@content-desc='webIcon']")
NOW_PLAYING_STATION_TEXT = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']//*[@resource-id='npsTitle']")
NOW_PLAYING_SONG_GENRE = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']//*[@resource-id='npsSubTitle']")
NOW_PLAYING_SONG_ARTIST = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']//*[@resource-id='npsSongArtist']")
NOW_PLAYING_SONG_TITLE = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']//*[@resource-id='npsSongTitle']")
NOW_PLAYING_OPERATION_PANEL = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@resource-id='de.eso.radio:id/operationPanelFlow']")
NOW_PLAYING_SKIP_BW_BUTTON = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@resource-id='de.eso.radio:id/nowPlayingBtnSkipPrevious']")
NOW_PLAYING_SKIP_BW_BUTTON_ICON = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@content-desc='###de.eso.radio:drawable/e82d_media_skip_backward']")
NOW_PLAYING_SKIP_FW_BUTTON = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@resource-id='de.eso.radio:id/nowPlayingBtnSkipNext']")
NOW_PLAYING_SKIP_FW_BUTTON_ICON = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@content-desc='###de.eso.radio:drawable/e82c_media_skip_forward']")
NOW_PLAYING_PLAY_PAUSE_BUTTON = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@content-desc='###btnPlayPause']")
NOW_PLAYING_PLAY_PAUSE_BUTTON_MUTE_ACTIVE = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@content-desc='###de.eso.radio:drawable/mute_active']")
NOW_PLAYING_PLAY_PAUSE_BUTTON_MUTE_INACTIVE = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@content-desc='###de.eso.radio:drawable/mute_inactive']")
NOW_PLAYING_FAVORITE_BUTTON = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@resource-id='de.eso.radio:id/nowPlayingBtnToggleFavorite']")
NOW_PLAYING_FAVORITE_BUTTON_ICON_ACTIVE = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@content-desc='###de.eso.radio:drawable/favorite_active']")
NOW_PLAYING_FAVORITE_BUTTON_ICON_INACTIVE = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@content-desc='###de.eso.radio:drawable/favorite_inactive']")
NOW_PLAYING_STREAMING_BUTTON = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@resource-id='de.eso.radio:id/streamingBtn']")
NOW_PLAYING_STREAMING_BUTTON_ICON = XpathString("//*[@resource-id='de.eso.radio:id/nowPlayingScreen']/..//*[@content-desc='###de.eso.radio:drawable/streaming_icon']")
NOW_PLAY_OPEN_HISTORY_BUTTON = XpathString("//*[@content-desc='###actionOpenRadioTextHistory']")
POPUP_DELETE_ALL = XpathString("//*[@content-desc='###de.eso.radio:string/texttool_globals_dialog_message___confirm_delete_all_items_from_list']//ancestor::*[@resource-id='android:id/parentPanel']")
POPUP_DELETE_ALL_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/texttool_globals_dialog_message___confirm_delete_all_items_from_list']")
POPUP_DELETE_ALL_NEGATIVE_BUTTON = XpathString("//*[@content-desc='###de.eso.radio:string/texttool_globals_dialog_message___confirm_delete_all_items_from_list']//ancestor::*[@resource-id='android:id/parentPanel']//*[@content-desc='dialogBtnNegative']")
POPUP_DELETE_ALL_POSITIVE_BUTTON = XpathString("//*[@content-desc='###de.eso.radio:string/texttool_globals_dialog_message___confirm_delete_all_items_from_list']//ancestor::*[@resource-id='android:id/parentPanel']//*[@content-desc='dialogBtnPositive']")
POPUP_PRIVACY_ACTIVE = XpathString("//*[@content-desc='###de.eso.radio:string/privacy_active_popup_dialog_message' or @content-desc='###de.eso.privacymode:string/texttool_globals_dialog_message___global_privacy_body']//ancestor::*[@resource-id='android:id/parentPanel']")
POPUP_PRIVACY_ACTIVE_TITLE = XpathString("//*[@content-desc='###de.eso.privacymode:string/texttool_globals_dialog_title___global_privacy_title']")
POPUP_PRIVACY_ACTIVE_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/privacy_active_popup_dialog_message' or @content-desc='###de.eso.privacymode:string/texttool_globals_dialog_message___global_privacy_body']")
POPUP_PRIVACY_ACTIVE_CANCEL_BUTTON = XpathString("//*[@content-desc='###de.eso.privacymode:string/texttool_globals_dialog_message___global_privacy_body']//ancestor::*[@resource-id='android:id/parentPanel']//*[@resource-id='android:id/buttonPanel']//*[@index='0'][@class='android.widget.Button']")
POPUP_PRIVACY_ACTIVE_OK_BUTTON = XpathString("//*[@content-desc='###de.eso.radio:string/privacy_active_popup_dialog_message']//ancestor::*[@resource-id='android:id/parentPanel']//*[@resource-id='android:id/buttonPanel']//*[@index='0'][@class='android.widget.Button']")
POPUP_PRIVACY_ACTIVE_PRIVACY_BUTTON = XpathString("//*[@content-desc='###de.eso.radio:string/privacy_active_popup_dialog_message' or @content-desc='###de.eso.privacymode:string/texttool_globals_dialog_message___global_privacy_body']//ancestor::*[@resource-id='android:id/parentPanel']//*[@resource-id='android:id/buttonPanel']//*[@index='1'][@class='android.widget.Button']")
POPUP_PRIVACY_ACTIVE_ONLINE_BUTTON = XpathString("//*[@content-desc='###de.eso.privacymode:string/texttool_globals_dialog_message___global_privacy_body']//ancestor::*[@resource-id='android:id/parentPanel']//*[@resource-id='android:id/buttonPanel']//*[@index='2'][@class='android.widget.Button']")
POPUP_STREAMING_SPOTIFY_NOT_INSTALLED = XpathString("//*[@content-desc='###de.eso.radio:string/streaming_service_spotify_not_installed']//ancestor::*[@resource-id='android:id/parentPanel']")
POPUP_STREAMING_SPOTIFY_NOT_INSTALLED_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/streaming_service_spotify_not_installed']")
POPUP_STREAMING_SPOTIFY_NOT_INSTALLED_NEGATIVE_BUTTON = XpathString("//*[@content-desc='###de.eso.radio:string/streaming_service_spotify_not_installed']//ancestor::*[@resource-id='android:id/parentPanel']//*[@content-desc='dialogBtnNegative']")
POPUP_STREAMING_SPOTIFY_NOT_INSTALLED_POSITIVE_BUTTON = XpathString("//*[@content-desc='###de.eso.radio:string/streaming_service_spotify_not_installed']//ancestor::*[@resource-id='android:id/parentPanel']//*[@content-desc='dialogBtnPositive']")
POPUP_STREAMING_SPOTIFY_NO_LOGIN = XpathString("//*[@content-desc='###de.eso.radio:string/streaming_service_spotify_not_logged_in']//ancestor::*[@resource-id='android:id/parentPanel']")
POPUP_STREAMING_SPOTIFY_NO_LOGIN_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/streaming_service_spotify_not_logged_in']")
POPUP_STREAMING_SPOTIFY_NO_LOGIN_NEGATIVE_BUTTON = XpathString("//*[@content-desc='###de.eso.radio:string/streaming_service_spotify_not_logged_in']//ancestor::*[@resource-id='android:id/parentPanel']//*[@content-desc='dialogBtnNegative']")
POPUP_STREAMING_SPOTIFY_NO_LOGIN_POSITIVE_BUTTON = XpathString("//*[@content-desc='###de.eso.radio:string/streaming_service_spotify_not_logged_in']//ancestor::*[@resource-id='android:id/parentPanel']//*[@content-desc='dialogBtnPositive']")
RADIOTEXT_HISTORY_CLOSE_BUTTON = XpathString("//*[@resource-id='de.eso.radio:id/titleLineActionCloseRtHistory'][@content-desc='###actionClose']")
RADIOTEXT_HISTORY_EMPTY_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_text_history_empty']")
RADIOTEXT_HISTORY_SOURCE_ICON = XpathString("//*[@resource-id='de.eso.radio:id/staticProviderLogoStartImageView'][@content-desc='###de.eso.radio:drawable/radio_current_source']")
RADIOTEXT_HISTORY_TITLE_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_text_history_title']")
RADIOTEXT_HISTORY_INDEX_0 = XpathString("//*[@content-desc='###listRadioTextHistory-list']/./*[@index='0']")
RADIOTEXT_HISTORY_INDEX_1 = XpathString("//*[@content-desc='###listRadioTextHistory-list']/./*[@index='1']")
SEARCH_BAR_CLEAR_BUTTON = XpathString("//*[@content-desc='###de.eso.radio:string/search_input_hint']/..//*[@resource-id='de.eso.radio:id/clearTextButton']")
SEARCH_BAR_SPEECH_BUTTON = XpathString("//*[@content-desc='###de.eso.radio:string/search_input_hint']/..//*[@resource-id='de.eso.radio:id/speechButton']")
SEARCH_DEVIDER_FAVORITES = XpathString("//*[@content-desc='###de.eso.radio:string/search_divider_favorites']")
SEARCH_DEVIDER_LAST_STATIONS = XpathString("//*[@content-desc='###de.eso.radio:string/search_divider_last_stations']")
SEARCH_DEVIDER_MANUAL_TUNE = XpathString("//*[@content-desc='###de.eso.radio:string/search_divider_manual_tune']")
SEARCH_DEVIDER_STATION_LIST = XpathString("//*[@content-desc='###de.eso.radio:string/search_divider_station_list']")
SEARCH_RESULTS_EMPTY_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/search_no_results']")
SETTINGS_BACK = XpathString("//*[contains(@content-desc, 'Back')]")
SETTINGS_SOURCE_ICON = XpathString("//*[@content-desc='###de.eso.radio:drawable/radio_current_source']")
SETTINGS_TITLE = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_title']")
SETTINGS_LIST_ITEM_AUTOMATIC_MUSIC_RECOGNITION = XpathString("//*[@content-desc='###AUTOMATIC_MUSIC_RECOGNITION']")
SETTINGS_LIST_ITEM_AUTOMATIC_MUSIC_RECOGNITION_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_provider_info_automatic_music_recognition']")
SETTINGS_LIST_ITEM_AUTOMATIC_MUSIC_RECOGNITION_TOGGLE_BUTTON = XpathString("//*[@content-desc='###AUTOMATIC_MUSIC_RECOGNITION-switch']")
SETTINGS_LIST_ITEM_CONNECTION_MANAGER = XpathString("//*[@content-desc='###CONNECTION_MANAGER']")
SETTINGS_LIST_ITEM_CONNECTION_MANAGER_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_connection_manager']")
SETTINGS_LIST_ITEM_DAB_ANNOUNCEMENT = XpathString("//*[@content-desc='###DAB_ANNOUNCEMENT']")
SETTINGS_LIST_ITEM_DAB_ANNOUNCEMENT_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_announcement_dab']")
SETTINGS_LIST_ITEM_DAB_ANNOUNCEMENT_TOGGLE_BUTTON = XpathString("//*[@content-desc='###DAB_ANNOUNCEMENT-switch']")
SETTINGS_LIST_ITEM_DISCLAIMER_OF_LIABILITY = XpathString("//*[@content-desc='###DISCLAIMER_OF_LIABILITY']")
SETTINGS_LIST_ITEM_DISCLAIMER_OF_LIABILITY_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_disclaimer_of_liabliltiy']")
SETTINGS_LIST_ITEM_DISPLAY_STATION_GENRES = XpathString("//*[@content-desc='###DISPLAY_STATION_GENRES']")
SETTINGS_LIST_ITEM_DISPLAY_STATION_GENRES_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_display_station_genres']")
SETTINGS_LIST_ITEM_DISPLAY_STATION_GENRES_TOGGLE_BUTTON = XpathString("//*[@content-desc='###DISPLAY_STATION_GENRES-switch']")
SETTINGS_LIST_ITEM_EMERGENCY_ANNOUNCEMENTS = XpathString("//*[@content-desc='###ALARM_ANNOUNCEMENT']")
SETTINGS_LIST_ITEM_EMERGENCY_ANNOUNCEMENTS_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_announcement_alarm']")
SETTINGS_LIST_ITEM_EMERGENCY_ANNOUNCEMENTS_TOGGLE_BUTTON = XpathString("//*[@content-desc='###ALARM_ANNOUNCEMENT-switch']")
SETTINGS_LIST_ITEM_IMPRINT = XpathString("//*[@content-desc='###IMPRINT']")
SETTINGS_LIST_ITEM_IMPRINT_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_imprint']")
SETTINGS_LIST_ITEM_ONLINE_STATION_TRACKING = XpathString("//*[@content-desc='###ONLINE_STATION_TRACKING']")
SETTINGS_LIST_ITEM_ONLINE_STATION_TRACKING_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_station_tracking_online']")
SETTINGS_LIST_ITEM_ONLINE_STATION_TRACKING_TOGGLE_BUTTON = XpathString("//*[@content-desc='###ONLINE_STATION_TRACKING-switch']")
SETTINGS_LIST_ITEM_OPEN_SOURCE_DISCLAIMER = XpathString("//*[@content-desc='###OPEN_SOURCE_DISCLAIMER']")
SETTINGS_LIST_ITEM_OPEN_SOURCE_DISCLAIMER_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_open_source_disclaimer']")
SETTINGS_LIST_ITEM_PRIVACY_NOTICE = XpathString("//*[@content-desc='###PRIVACY_NOTICE']")
SETTINGS_LIST_ITEM_PRIVACY_NOTICE_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_privacy_notice']")
SETTINGS_LIST_ITEM_PREFERRED_PICTURE_MODE = XpathString("//*[@content-desc='###preferred_image_type']")
SETTINGS_LIST_ITEM_PREFERRED_PICTURE_MODE_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_preferred_image_type']")
SETTINGS_LIST_ITEM_PREFERRED_PICTURE_MODE_BUTTON_CONTENT_COVER = XpathString("//*[@content-desc='###preferred_image_type']/.//*[@content-desc='###CONTENT_COVER']")
SETTINGS_LIST_ITEM_PREFERRED_PICTURE_MODE_BUTTON_CONTENT_COVER_ACTIVE = XpathString("//*[@content-desc='###preferred_image_type']/.//*[@content-desc='###CONTENT_COVER'][@checked='true']")
SETTINGS_LIST_ITEM_PREFERRED_PICTURE_MODE_BUTTON_CONTENT_COVER_INACTIVE = XpathString("//*[@content-desc='###preferred_image_type']/.//*[@content-desc='###CONTENT_COVER'][@checked='false']")
SETTINGS_LIST_ITEM_PREFERRED_PICTURE_MODE_BUTTON_SLIDE_SHOW = XpathString("//*[@content-desc='###preferred_image_type']/.//*[@content-desc='###SLIDE_SHOW'][@checked='false']")
SETTINGS_LIST_ITEM_PREFERRED_PICTURE_MODE_BUTTON_SLIDE_SHOW_ACTIVE = XpathString("//*[@content-desc='###preferred_image_type']/.//*[@content-desc='###SLIDE_SHOW'][@checked='true']")
SETTINGS_LIST_ITEM_PREFERRED_PICTURE_MODE_BUTTON_SLIDE_SHOW_INACTIVE = XpathString("//*[@content-desc='###preferred_image_type']/.//*[@content-desc='###SLIDE_SHOW'][@checked='false']")
SETTINGS_LIST_ITEM_PREFERRED_PICTURE_MODE_BUTTON_STATION_LOGO = XpathString("//*[@content-desc='###preferred_image_type']/.//*[@content-desc='###STATION_LOGO']")
SETTINGS_LIST_ITEM_PREFERRED_PICTURE_MODE_BUTTON_STATION_LOGO_ACTIVE = XpathString("//*[@content-desc='###preferred_image_type']/.//*[@content-desc='###STATION_LOGO'][@checked='true']")
SETTINGS_LIST_ITEM_PREFERRED_PICTURE_MODE_BUTTON_STATION_LOGO_INACTIVE = XpathString("//*[@content-desc='###preferred_image_type']/.//*[@content-desc='###STATION_LOGO'][@checked='false']")
SETTINGS_LIST_ITEM_PREFERRED_STREAMING_QUALITY = XpathString("//*[@content-desc='###preferred_data_rate']")
SETTINGS_LIST_ITEM_PREFERRED_STREAMING_QUALITY_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_preferred_data_rate']")
SETTINGS_LIST_ITEM_PREFERRED_STREAMING_QUALITY_BUTTON_HIGH = XpathString("//*[@content-desc='###preferred_data_rate']/.//*[@content-desc='###HIGH']")
SETTINGS_LIST_ITEM_PREFERRED_STREAMING_QUALITY_BUTTON_HIGH_ACTIVE = XpathString("//*[@content-desc='###preferred_data_rate']/.//*[@content-desc='###HIGH'][@checked='true']")
SETTINGS_LIST_ITEM_PREFERRED_STREAMING_QUALITY_BUTTON_HIGH_INACTIVE = XpathString("//*[@content-desc='###preferred_data_rate']/.//*[@content-desc='###HIGH'][@checked='false']")
SETTINGS_LIST_ITEM_PREFERRED_STREAMING_QUALITY_BUTTON_LOW = XpathString("//*[@content-desc='###preferred_data_rate']/.//*[@content-desc='###LOW']")
SETTINGS_LIST_ITEM_PREFERRED_STREAMING_QUALITY_BUTTON_LOW_ACTIVE = XpathString("//*[@content-desc='###preferred_data_rate']/.//*[@content-desc='###LOW'][@checked='true']")
SETTINGS_LIST_ITEM_PREFERRED_STREAMING_QUALITY_BUTTON_LOW_INACTIVE = XpathString("//*[@content-desc='###preferred_data_rate']/.//*[@content-desc='###LOW'][@checked='false']")
SETTINGS_LIST_ITEM_PROVIDER_INFO = XpathString("//*[@content-desc='###PROVIDER_INFO']")
SETTINGS_LIST_ITEM_PROVIDER_INFO_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_provider_info']")
SETTINGS_LIST_ITEM_STATION_TRACKING = XpathString("//*[@content-desc='###SOFT_LINKING']")
SETTINGS_LIST_ITEM_STATION_TRACKING_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_softlinking']")
SETTINGS_LIST_ITEM_STATION_TRACKING_TOGGLE_BUTTON = XpathString("//*[@content-desc='###SOFT_LINKING-switch']")
SETTINGS_LIST_ITEM_TERMS_OF_USE = XpathString("//*[@content-desc='###TERMS_OF_USE']")
SETTINGS_LIST_ITEM_TERMS_OF_USE_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_terms_of_use']")
SETTINGS_LIST_ITEM_TRAFFIC_ANNOUNCEMENT = XpathString("//*[@content-desc='###TRAFFIC_ANNOUNCEMENT']")
SETTINGS_LIST_ITEM_TRAFFIC_ANNOUNCEMENT_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_announcement_traffic']")
SETTINGS_LIST_ITEM_TRAFFIC_ANNOUNCEMENT_TOGGLE_BUTTON = XpathString("//*[@content-desc='###TRAFFIC_ANNOUNCEMENT-switch']")
SETTINGS_LIST_ITEM_SOUND_SETTINGS = XpathString("//*[@content-desc='###SOUND_SETTINGS']")
SETTINGS_LIST_ITEM_SOUND_SETTINGS_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_sound_settings']")
SETTINGS_PROVIDER_INFO_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_provider_info_text']")
SETTINGS_PROVIDER_INFO_SUB_TEXT = XpathString("//*[@content-desc='###de.eso.radio:string/radio_settings_provider_info_subtext']")
SETTINGS_PROVIDER_INFO_GRACENOTE_LOGO = XpathString("//*[@content-desc='###de.eso.radio:drawable/gracenote_logo']")
SETTINGS_OSD_BLOCKING = XpathString("//*[@content-desc='###de.eso.radio:string/texttool_globals_hmisdk_blocking_disclaimer___disclaimer_text_blocking']")
SETTINGS_OSD_TO_TOP_BUTTON = XpathString("//*[@package='de.eso.radio'][@content-desc='###LongTextDisclaimer-goToTopAction']")
SETTINGS_OSD_TOP = XpathString("//*[@package='de.eso.radio'][contains(@content-desc, 'disclaimerPart-0')]")

STATION_88_0_ITEM = XpathString("//*[@content-desc='###88.0 MHz']")
STATION_88_0_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###88.0 MHz']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_88_0_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###88.0 MHz']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_88_0_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###88.0 MHz']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_88_0_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###88.0 MHz']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_88_0_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###88.0 MHz']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_88_0_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###88.0 MHz']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_88_0_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###88.0 MHz']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_88_0_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###88.0 MHz']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_88_0_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###88.0 MHz']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_88_0_PLAYER_NPS = XpathString("//*[@package='de.eso.radio'][@resource-id='npsTitle'][@text='88.0 MHz']")
STATION_88_0_PLAYER_MINIPLAYER = XpathString("//*[@package='de.eso.radio'][@resource-id='miniPlayerMainInfo'][@text='88.0 MHz']")
STATION_89_0_PLAYER_NPS = XpathString("//*[@package='de.eso.radio'][@resource-id='npsTitle'][@text='89.0 MHz']")
STATION_89_0_PLAYER_MINIPLAYER = XpathString("//*[@package='de.eso.radio'][@resource-id='miniPlayerMainInfo'][@text='89.0 MHz']")
STATION_90_0_PLAYER_NPS = XpathString("//*[@package='de.eso.radio'][@resource-id='npsTitle'][@text='90.0 MHz']")
STATION_90_0_PLAYER_MINIPLAYER = XpathString("//*[@package='de.eso.radio'][@resource-id='miniPlayerMainInfo'][@text='90.0 MHz']")
STATION_ANTENNE_BAYERN_ITEM = XpathString("//*[@content-desc='###ANTENNE BAYERN']")
STATION_ANTENNE_BAYERN_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###ANTENNE BAYERN']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_ANTENNE_BAYERN_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###ANTENNE BAYERN']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_ANTENNE_BAYERN_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###ANTENNE BAYERN']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_ANTENNE_BAYERN_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###ANTENNE BAYERN']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_ANTENNE_BAYERN_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###ANTENNE BAYERN']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_ANTENNE_BAYERN_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###ANTENNE BAYERN']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_ANTENNE_BAYERN_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###ANTENNE BAYERN']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_ANTENNE_BAYERN_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###ANTENNE BAYERN']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_ANTENNE_BAYERN_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###ANTENNE BAYERN']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_ARABELLA_BAYERN_ITEM = XpathString("//*[@content-desc='###ARABELLA BAYERN']")
STATION_ARABELLA_BAYERN_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###ARABELLA BAYERN']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_ARABELLA_BAYERN_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###ARABELLA BAYERN']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_ARABELLA_BAYERN_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###ARABELLA BAYERN']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_ARABELLA_BAYERN_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###ARABELLA BAYERN']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_ARABELLA_BAYERN_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###ARABELLA BAYERN']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_ARABELLA_BAYERN_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###ARABELLA BAYERN']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_ARABELLA_BAYERN_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###ARABELLA BAYERN']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_ARABELLA_BAYERN_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###ARABELLA BAYERN']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_ARABELLA_BAYERN_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###ARABELLA BAYERN']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BAYERN_1_FRANKEN_ITEM = XpathString("//*[@content-desc='###BAYERN 1 Franken']")
STATION_BAYERN_1_FRANKEN_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Franken']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_BAYERN_1_FRANKEN_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###BAYERN 1 Franken']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BAYERN_1_FRANKEN_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Franken']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_BAYERN_1_FRANKEN_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###BAYERN 1 Franken']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_BAYERN_1_FRANKEN_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Franken']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_BAYERN_1_FRANKEN_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###BAYERN 1 Franken']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_BAYERN_1_FRANKEN_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###BAYERN 1 Franken']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_BAYERN_1_FRANKEN_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Franken']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_BAYERN_1_FRANKEN_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###BAYERN 1 Franken']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BAYERN_1_MAIN_ITEM = XpathString("//*[@content-desc='###BAYERN 1 Main']")
STATION_BAYERN_1_MAIN_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Main']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_BAYERN_1_MAIN_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###BAYERN 1 Main']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BAYERN_1_MAIN_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Main']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_BAYERN_1_MAIN_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###BAYERN 1 Main']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_BAYERN_1_MAIN_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Main']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_BAYERN_1_MAIN_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###BAYERN 1 Main']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_BAYERN_1_MAIN_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###BAYERN 1 Main']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_BAYERN_1_MAIN_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Main']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_BAYERN_1_MAIN_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###BAYERN 1 Main']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BAYERN_1_NBY_OPF_ITEM = XpathString("//*[@content-desc='###BAYERN 1 Nby/Opf']")
STATION_BAYERN_1_NBY_OPF_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Nby/Opf']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_BAYERN_1_NBY_OPF_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###BAYERN 1 Nby/Opf']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BAYERN_1_NBY_OPF_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Nby/Opf']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_BAYERN_1_NBY_OPF_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###BAYERN 1 Nby/Opf']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_BAYERN_1_NBY_OPF_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Nby/Opf']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_BAYERN_1_NBY_OPF_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###BAYERN 1 Nby/Opf']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_BAYERN_1_NBY_OPF_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###BAYERN 1 Nby/Opf']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_BAYERN_1_NBY_OPF_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Nby/Opf']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_BAYERN_1_NBY_OPF_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###BAYERN 1 Nby/Opf']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BAYERN_1_OBB_ITEM = XpathString("//*[@content-desc='###BAYERN 1 Obb']")
STATION_BAYERN_1_OBB_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Obb']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_BAYERN_1_OBB_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###BAYERN 1 Obb']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BAYERN_1_OBB_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Obb']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_BAYERN_1_OBB_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###BAYERN 1 Obb']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_BAYERN_1_OBB_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Obb']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_BAYERN_1_OBB_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###BAYERN 1 Obb']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_BAYERN_1_OBB_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###BAYERN 1 Obb']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_BAYERN_1_OBB_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Obb']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_BAYERN_1_OBB_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###BAYERN 1 Obb']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BAYERN_1_SCHW_ITEM = XpathString("//*[@content-desc='###BAYERN 1 Schw']")
STATION_BAYERN_1_SCHW_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Schw']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_BAYERN_1_SCHW_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###BAYERN 1 Schw']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BAYERN_1_SCHW_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Schw']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_BAYERN_1_SCHW_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###BAYERN 1 Schw']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_BAYERN_1_SCHW_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Schw']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_BAYERN_1_SCHW_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###BAYERN 1 Schw']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_BAYERN_1_SCHW_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###BAYERN 1 Schw']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_BAYERN_1_SCHW_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###BAYERN 1 Schw']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_BAYERN_1_SCHW_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###BAYERN 1 Schw']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BAYERN_2_ITEM = XpathString("//*[@content-desc='###Bayern 2']")
STATION_BAYERN_2_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###Bayern 2']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_BAYERN_2_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###Bayern 2']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BAYERN_2_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###Bayern 2']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_BAYERN_2_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###Bayern 2']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_BAYERN_2_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###Bayern 2']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_BAYERN_2_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###Bayern 2']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_BAYERN_2_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###Bayern 2']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_BAYERN_2_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###Bayern 2']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_BAYERN_2_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###Bayern 2']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BAYERN_3_ITEM = XpathString("//*[@content-desc='###BAYERN 3']")
STATION_BAYERN_3_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###BAYERN 3']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_BAYERN_3_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###BAYERN 3']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BAYERN_3_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###BAYERN 3']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_BAYERN_3_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###BAYERN 3']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_BAYERN_3_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###BAYERN 3']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_BAYERN_3_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###BAYERN 3']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_BAYERN_3_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###BAYERN 3']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_BAYERN_3_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###BAYERN 3']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_BAYERN_3_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###BAYERN 3']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BR_HEIMAT_ITEM = XpathString("//*[@content-desc='###BR Heimat']")
STATION_BR_HEIMAT_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###BR Heimat']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_BR_HEIMAT_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###BR Heimat']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BR_HEIMAT_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###BR Heimat']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_BR_HEIMAT_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###BR Heimat']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_BR_HEIMAT_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###BR Heimat']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_BR_HEIMAT_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###BR Heimat']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_BR_HEIMAT_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###BR Heimat']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_BR_HEIMAT_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###BR Heimat']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_BR_HEIMAT_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###BR Heimat']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BR_SCHLAGER_ITEM = XpathString("//*[@content-desc='###BR Schlager']")
STATION_BR_SCHLAGER_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###BR Schlager']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_BR_SCHLAGER_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###BR Schlager']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BR_SCHLAGER_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###BR Schlager']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_BR_SCHLAGER_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###BR Schlager']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_BR_SCHLAGER_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###BR Schlager']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_BR_SCHLAGER_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###BR Schlager']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_BR_SCHLAGER_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###BR Schlager']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_BR_SCHLAGER_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###BR Schlager']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_BR_SCHLAGER_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###BR Schlager']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BR_VERKEHR_ITEM = XpathString("//*[@content-desc='###BR Verkehr']")
STATION_BR_VERKEHR_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###BR Verkehr']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_BR_VERKEHR_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###BR Verkehr']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BR_VERKEHR_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###BR Verkehr']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_BR_VERKEHR_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###BR Verkehr']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_BR_VERKEHR_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###BR Verkehr']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_BR_VERKEHR_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###BR Verkehr']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_BR_VERKEHR_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###BR Verkehr']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_BR_VERKEHR_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###BR Verkehr']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_BR_VERKEHR_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###BR Verkehr']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BR_KLASSIK_ITEM = XpathString("//*[@content-desc='###BR-KLASSIK']")
STATION_BR_KLASSIK_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###BR-KLASSIK']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_BR_KLASSIK_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###BR-KLASSIK']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BR_KLASSIK_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###BR-KLASSIK']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_BR_KLASSIK_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###BR-KLASSIK']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_BR_KLASSIK_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###BR-KLASSIK']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_BR_KLASSIK_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###BR-KLASSIK']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_BR_KLASSIK_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###BR-KLASSIK']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_BR_KLASSIK_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###BR-KLASSIK']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_BR_KLASSIK_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###BR-KLASSIK']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BR24_ITEM = XpathString("//*[@content-desc='###BR24']")
STATION_BR24_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###BR24']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_BR24_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###BR24']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BR24_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###BR24']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_BR24_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###BR24']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_BR24_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###BR24']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_BR24_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###BR24']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_BR24_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###BR24']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_BR24_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###BR24']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_BR24_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###BR24']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BR24LIVE_ITEM = XpathString("//*[@content-desc='###BR24live']")
STATION_BR24LIVE_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###BR24live']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_BR24LIVE_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###BR24live']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_BR24LIVE_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###BR24live']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_BR24LIVE_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###BR24live']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_BR24LIVE_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###BR24live']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_BR24LIVE_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###BR24live']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_BR24LIVE_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###BR24live']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_BR24LIVE_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###BR24live']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_BR24LIVE_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###BR24live']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_EGOFM_ITEM = XpathString("//*[@content-desc='###egoFM']")
STATION_EGOFM_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###egoFM']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_EGOFM_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###egoFM']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_EGOFM_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###egoFM']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_EGOFM_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###egoFM']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_EGOFM_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###egoFM']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_EGOFM_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###egoFM']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_EGOFM_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###egoFM']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_EGOFM_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###egoFM']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_EGOFM_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###egoFM']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_PULS_ITEM = XpathString("//*[@content-desc='###PULS']")
STATION_PULS_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###PULS']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_PULS_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###PULS']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_PULS_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###PULS']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_PULS_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###PULS']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_PULS_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###PULS']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_PULS_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###PULS']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_PULS_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###PULS']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_PULS_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###PULS']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_PULS_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###PULS']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_RADIO_TEDDY_ITEM = XpathString("//*[@content-desc='###RADIO TEDDY']")
STATION_RADIO_TEDDY_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###RADIO TEDDY']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_RADIO_TEDDY_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###RADIO TEDDY']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_RADIO_TEDDY_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###RADIO TEDDY']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_RADIO_TEDDY_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###RADIO TEDDY']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_RADIO_TEDDY_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###RADIO TEDDY']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_RADIO_TEDDY_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###RADIO TEDDY']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_RADIO_TEDDY_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###RADIO TEDDY']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_RADIO_TEDDY_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###RADIO TEDDY']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_RADIO_TEDDY_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###RADIO TEDDY']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_ROCK_ANTENNE_BAY_ITEM = XpathString("//*[@content-desc='###ROCK ANTENNE BAY']")
STATION_ROCK_ANTENNE_BAY_FAVORITE_GENRE_TEXT = XpathString("//*[@content-desc='###ROCK ANTENNE BAY']/./*[@resource-id='de.eso.radio:id/listItemTileItemSubTitle']")
STATION_ROCK_ANTENNE_BAY_FAVORITE_STATION_LOGO = XpathString("//*[@content-desc='###ROCK ANTENNE BAY']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
STATION_ROCK_ANTENNE_BAY_FAVORITE_STATION_TEXT = XpathString("//*[@content-desc='###ROCK ANTENNE BAY']/./*[@resource-id='de.eso.radio:id/listItemTileItemTitle']")
STATION_ROCK_ANTENNE_BAY_BROWSER_FAVORITE_ICON = XpathString("//*[@content-desc='###ROCK ANTENNE BAY']/.//*[@content-desc='###listBrowserToggleFavorite']")
STATION_ROCK_ANTENNE_BAY_BROWSER_GENRE_TEXT = XpathString("//*[@content-desc='###ROCK ANTENNE BAY']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textEnd']")
STATION_ROCK_ANTENNE_BAY_BROWSER_RECEPTION_ICON = XpathString("//*[@content-desc='###ROCK ANTENNE BAY']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_iconEnd']")
STATION_ROCK_ANTENNE_BAY_BROWSER_RECEPTION_ICON_DAB_HYBRID = XpathString("//*[@content-desc='###ROCK ANTENNE BAY']/.//*[@content-desc='###de.eso.radio:drawable/source_dab_hybrid']")
STATION_ROCK_ANTENNE_BAY_BROWSER_STATION_TEXT = XpathString("//*[@content-desc='###ROCK ANTENNE BAY']/.//*[@resource-id='de.eso.radio:id/listItemGrid2MainContent_textStart']")
STATION_ROCK_ANTENNE_BAY_BROWSER_STATION_LOGO = XpathString("//*[@content-desc='###ROCK ANTENNE BAY']/./*[@class='android.widget.FrameLayout']/./*[@class='android.widget.ImageView']")
