# -*- coding: utf-8 -*-
"""Module contains xpath of launcher app."""
import enna_hcp_configuration.android.xpaths
from . import XpathString

if enna_hcp_configuration.android.xpaths.CLUSTER == enna_hcp_configuration.android.xpaths.SupportedClusters.CLU55:
	from enna_hcp_configuration.texts.CLU55.center.de.eso.car import audi as car_settings
elif enna_hcp_configuration.android.xpaths.CLUSTER == enna_hcp_configuration.android.xpaths.SupportedClusters.CLU53:
	from enna_hcp_configuration.texts.CLU53.center.de.eso.car import audi as car_settings
elif enna_hcp_configuration.android.xpaths.CLUSTER == enna_hcp_configuration.android.xpaths.SupportedClusters.CLU51:
	from enna_hcp_configuration.texts.CLU51.center.de.eso.car import audi as car_settings
elif enna_hcp_configuration.android.xpaths.CLUSTER == enna_hcp_configuration.android.xpaths.SupportedClusters.CLU48:
	from enna_hcp_configuration.texts.CLU48.center.de.eso.car import audi as car_settings
else:
	from enna_hcp_configuration.texts.CLU46.center.de.eso.car import audi as car_settings


PRESETS_TITLE = XpathString("//*[@class='android.widget.HorizontalScrollView']/.//*[@resource-id='de.eso.sound.audi:string/ti_tab_presets' and @selected='true']")
PRESETS_CONCERTS_TITLE = XpathString("//*[@resource-id='de.eso.sound.audi:id/concert' and @checked='true']/../../../../..//*[@class='android.widget.HorizontalScrollView']/.//*[@resource-id='de.eso.sound.audi:string/ti_tab_presets' and @selected='true']")  # pylint: disable=line-too-long # noqa
PRESETS_NEUTRAL_TITLE = XpathString("//*[@resource-id='de.eso.sound.audi:id/neutral' and @checked='true']/../../../../..//*[@class='android.widget.HorizontalScrollView']/.//*[@resource-id='de.eso.sound.audi:string/ti_tab_presets' and @selected='true']")  # pylint: disable=line-too-long # noqa
PRESETS_LOUNGE_TITLE = XpathString("//*[@resource-id='de.eso.sound.audi:id/lounge' and @checked='true']/../../../../..//*[@class='android.widget.HorizontalScrollView']/.//*[@resource-id='de.eso.sound.audi:string/ti_tab_presets' and @selected='true']")  # pylint: disable=line-too-long # noqa
PRESETS_POTCAST_TITLE = XpathString("//*[@resource-id='de.eso.sound.audi:id/podcast' and @checked='true']/../../../../..//*[@class='android.widget.HorizontalScrollView']/.//*[@resource-id='de.eso.sound.audi:string/ti_tab_presets' and @selected='true']")  # pylint: disable=line-too-long # noqa
PRESETS_INDIVIDUAL_TITLE = XpathString("//*[@resource-id='de.eso.sound.audi:id/individual' and @checked='true']/../../../../..//*[@class='android.widget.HorizontalScrollView']/.//*[@resource-id='de.eso.sound.audi:string/ti_tab_presets' and @selected='true']")  # pylint: disable=line-too-long # noqa
PRESETS_INDIVIDUAL_EQUALIZER_NO_PREMIUM_TITLE = XpathString("//*[@resource-id='de.eso.sound.audi:id/titleArea']/.//*[@content-desc='###de.eso.sound.audi:string/sound_tab_bar__equalizer_tab']")
PRESETS_INDIVIDUAL_EQUALIZER_TITLE = XpathString("//*[@class='android.widget.HorizontalScrollView']/.//*[@resource-id='de.eso.sound.audi:string/ti_tab_equalizer' and @selected='true']")
PRESETS_INDIVIDUAL_SURROUND_TITLE = XpathString("//*[@class='android.widget.HorizontalScrollView']/.//*[@resource-id='de.eso.sound.audi:string/ti_tab_surround' and @selected='true']")
PRESETS_INDIVIDUAL_SEATS_TITLE = XpathString("//*[@class='android.widget.HorizontalScrollView']/.//*[@resource-id='de.eso.sound.audi:string/ti_tab_seats' and @selected='true']")
BALANCE_FADER_TITLE = XpathString("//*[@class='android.widget.HorizontalScrollView']/.//*[@resource-id='de.eso.sound.audi:string/ti_tab_balance_fader' and @selected='true']")
VOLUME_TITLE = XpathString("//*[@class='android.widget.HorizontalScrollView']/.//*[@resource-id='de.eso.sound.audi:string/ti_tab_volumes' and @selected='true']")
VOLUME_TITLE_UNSELECTED = XpathString("//*[@class='android.widget.HorizontalScrollView']/.//*[@resource-id='de.eso.sound.audi:string/ti_tab_volumes' and @selected='false']")
VOLUME_OPEN_SOURCE_DISCLAIMER_TITLE = XpathString("//*[@resource-id='de.eso.sound.audi:id/titleTextViewRef' and @content-desc='###de.eso.sound.audi:string/screen_title__disclaimer']")
FOD_TITLE = XpathString("//*[@class='android.widget.HorizontalScrollView']/.//*[@resource-id='de.eso.sound.audi:string/ti_tab_extras' and @selected='true']")
LIST_CONTAINER = XpathString("//*[@class='androidx.recyclerview.widget.RecyclerView']")

BACK_BUTTON = XpathString(f"//*{str(car_settings.departure_time_setup_back).replace('@text', '@content-desc')}")
BALANCE_FADER_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:string/ti_tab_balance_fader']")
VOLUME_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:string/ti_tab_volumes']")
FOD_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:string/ti_tab_extras']")
PRESETS_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:string/ti_tab_presets']")
VOLUME_OSD_BUTTON = XpathString("//*[@content-desc='###ListItemOpenSourceDisclaimer']")
VOLUME_RECYCLERVIEW_LIST = XpathString("//*[@class='androidx.recyclerview.widget.RecyclerView']")
PRESET_NEUTRAL_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/neutral']")
PRESET_LOUNGE_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/lounge']")
PRESET_POTCAST_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/podcast']")
PRESET_INDIVIDUAL_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/individual']")
PRESET_CONCERTS_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/concert']")
PRESET_INDIVIDUAL_EDIT_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/presetEditIndividual']")
PRESET_INDIVIDUAL_SURROUND_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:string/ti_tab_surround']")
PRESET_INDIVIDUAL_SEATS_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:string/ti_tab_seats']")
PRESET_INDIVIDUAL_EQUALIZER_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:string/ti_tab_equalizer']")

# xpath_names for sound test cases
FOD_LIST_ITEM_AUTO_LEVEL_ADJUSTMENT = XpathString("//*[@content-desc='###ListItemAutoLevelAdjustment']")
FOD_LIST_ITEM_AUTO_LEVEL_ADJUSTMENT_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_auto_level_adjustment']")
FOD_LIST_ITEM_AUTO_LEVEL_ADJUSTMENT_TOGGLE_BUTTON = XpathString("//*[@content-desc='###ListItemAutoLevelAdjustment-switch']")
FOD_LIST_ITEM_BASS_BOOST = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_bass_boost']/../..")
FOD_LIST_ITEM_BASS_BOOST_SUB_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_bass_boost_subText']")
FOD_LIST_ITEM_BASS_BOOST_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_bass_boost']")
FOD_LIST_ITEM_BASS_BOOST_TOGGLE_BUTTON = XpathString("//*[@content-desc='###ListItemBassBoost-switch']")
FOD_LIST_ITEM_LOW_BIT_ENHANCEMENT = XpathString("//*[@content-desc='###ListItemLowBitEnhancement']")
FOD_LIST_ITEM_LOW_BIT_ENHANCEMENT_SUB_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_low_bit_enhancement_subText']")
FOD_LIST_ITEM_LOW_BIT_ENHANCEMENT_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_low_bit_enhancement']")
FOD_LIST_ITEM_LOW_BIT_ENHANCEMENT_TOGGLE_BUTTON = XpathString("//*[@content-desc='###ListItemLowBitEnhancement-switch']")
FOD_LIST_ITEM_VIRTUAL_SURROUND = XpathString("//*[@content-desc='###ListItemVirtualSurround']")
FOD_LIST_ITEM_VIRTUAL_SURROUND_SUB_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_virtual_surround_subText']")
FOD_LIST_ITEM_VIRTUAL_SURROUND_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_virtual_surround']")
FOD_LIST_ITEM_VIRTUAL_SURROUND_TOGGLE_BUTTON = XpathString("//*[@content-desc='###ListItemVirtualSurround-switch']")
FOD_VIRTUAL_ENVIRONMENT = XpathString("//*[@content-desc='###ListItemVirtualEnvironment']")
FOD_VIRTUAL_ENVIRONMENT_CLOSED_BUTTON = XpathString("//*[@content-desc='###ListItemVirtualEnvironment']/.//*[@content-desc='###de.eso.sound.audi:drawable/unfoldable_triangle']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_CONCERT_HALL = XpathString("//*[@package='de.eso.sound.audi' and @content-desc='###CONCERT_HALL']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_CONCERT_HALL_RADIO_BUTTON = XpathString("//*[@package='de.eso.sound.audi' and @content-desc='###CONCERT_HALL-radio']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_CONCERT_HALL_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__virtual_environment_concert_hall']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_JAZZ_CLUB = XpathString("//*[@package='de.eso.sound.audi' and @content-desc='###JAZZ_CLUB']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_JAZZ_CLUB_RADIO_BUTTON = XpathString("//*[@package='de.eso.sound.audi' and @content-desc='###JAZZ_CLUB-radio']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_JAZZ_CLUB_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__virtual_environment_jazz_club']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_LIVING_ROOM = XpathString("//*[@package='de.eso.sound.audi' and @content-desc='###LIVING_ROOM']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_LIVING_ROOM_RADIO_BUTTON = XpathString("//*[@package='de.eso.sound.audi' and @content-desc='###LIVING_ROOM-radio']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_LIVING_ROOM_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__virtual_environment_living_room']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_OFF = XpathString("//*[@package='de.eso.sound.audi' and @content-desc='###OFF']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_OFF_RADIO_BUTTON = XpathString("//*[@package='de.eso.sound.audi' and @content-desc='###OFF-radio']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_OFF_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__virtual_environment_off']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_STUDIO = XpathString("//*[@package='de.eso.sound.audi' and @content-desc='###STUDIO']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_STUDIO_RADIO_BUTTON = XpathString("//*[@package='de.eso.sound.audi' and @content-desc='###STUDIO-radio']")
FOD_VIRTUAL_ENVIRONMENT_LIST_ITEM_STUDIO_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__virtual_environment_recording_studio']")
FOD_VIRTUAL_ENVIRONMENT_OPENED_BUTTON = XpathString("//*[@content-desc='###ListItemVirtualEnvironment']/.//*[@content-desc='###de.eso.sound.audi:drawable/foldable_triangle']")
FOD_VIRTUAL_ENVIRONMENT_SELECTED_TEXT = XpathString("//*[@resource-id='de.eso.sound.audi:id/listItemGrid2MainContent_textEnd']")
FOD_VIRTUAL_ENVIRONMENT_SUB_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__virtual_environment_subText']")
FOD_VIRTUAL_ENVIRONMENT_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_virtual_environment']")

PRESET_INDIVIDUAL_EQUALIZER_PROFILES_LIST_TITLE_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/equalizer_tab__drop_down_focus_title']")
PRESET_INDIVIDUAL_EQUALIZER_PROFILES_LIST_SELECTED_TEXT = XpathString("//*[@resource-id='de.eso.sound.audi:id/dropdown_focus']/.//*[@resource-id='de.eso.sound.audi:id/spinnerItemText']")
PRESET_INDIVIDUAL_EQUALIZER_PROFILES_LIST_POSITION_ALL = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__preset_position_all']/..")
PRESET_INDIVIDUAL_EQUALIZER_PROFILES_LIST_POSITION_ALL_RADIO_BUTTON = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__preset_position_all']/..//*[@resource-id='de.eso.sound.audi:id/spinnerItemRadioButton']")
PRESET_INDIVIDUAL_EQUALIZER_PROFILES_LIST_POSITION_ALL_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__preset_position_all']")
PRESET_INDIVIDUAL_EQUALIZER_PROFILES_LIST_POSITION_FRONT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__preset_position_front']/..")
PRESET_INDIVIDUAL_EQUALIZER_PROFILES_LIST_POSITION_FRONT_RADIO_BUTTON = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__preset_position_front']/..//*[@resource-id='de.eso.sound.audi:id/spinnerItemRadioButton']")
PRESET_INDIVIDUAL_EQUALIZER_PROFILES_LIST_POSITION_FRONT_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__preset_position_front']")
PRESET_INDIVIDUAL_EQUALIZER_PROFILES_LIST_POSITION_REAR = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__preset_position_rear']/..")
PRESET_INDIVIDUAL_EQUALIZER_PROFILES_LIST_POSITION_REAR_RADIO_BUTTON = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__preset_position_rear']/..//*[@resource-id='de.eso.sound.audi:id/spinnerItemRadioButton']")
PRESET_INDIVIDUAL_EQUALIZER_PROFILES_LIST_POSITION_REAR_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__preset_position_rear']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_BASS = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_bass']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_BASS_MAX_TEXT = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_bass']/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_max']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_BASS_MINUS_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_bass']/.//*[@resource-id='de.eso.sound.audi:id/minusButton']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_BASS_MIN_TEXT = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_bass']/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_min']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_BASS_PLUS_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_bass']/.//*[@resource-id='de.eso.sound.audi:id/plusButton']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_BASS_SEEK_BAR = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_bass']/.//*[@resource-id='de.eso.sound.audi:id/seekBar']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_BASS_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/equalizer_tab__bass_slider_title']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_SUBWOOFER = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_subwoofer']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_SUBWOOFER_MAX_TEXT = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_subwoofer']/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_max']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_SUBWOOFER_MINUS_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_subwoofer']/.//*[@resource-id='de.eso.sound.audi:id/minusButton']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_SUBWOOFER_MIN_TEXT = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_subwoofer']/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_min']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_SUBWOOFER_PLUS_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_subwoofer']/.//*[@resource-id='de.eso.sound.audi:id/plusButton']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_SUBWOOFER_SEEK_BAR = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_subwoofer']/.//*[@resource-id='de.eso.sound.audi:id/seekBar']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_SUBWOOFER_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/equalizer_tab__subwoofer_slider_title']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_TREBLE = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_treble']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_TREBLE_MAX_TEXT = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_treble']/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_max']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_TREBLE_MINUS_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_treble']/.//*[@resource-id='de.eso.sound.audi:id/minusButton']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_TREBLE_MIN_TEXT = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_treble']/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_min']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_TREBLE_PLUS_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_treble']/.//*[@resource-id='de.eso.sound.audi:id/plusButton']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_TREBLE_SEEK_BAR = XpathString("//*[@resource-id='de.eso.sound.audi:id/slider_treble']/.//*[@resource-id='de.eso.sound.audi:id/seekBar']")
PRESET_INDIVIDUAL_EQUALIZER_SLIDER_TREBLE_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/equalizer_tab__treble_slider_title']")
PRESET_INDIVIDUAL_EQUALIZER_SOUNDEXPERIENCE_IMAGE = XpathString("//*[@resource-id='de.eso.sound.audi:id/image_focus']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_CO_DRIVER_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/seats_headrest_button_right']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_CO_DRIVER_DECORATOR_IMAGE = XpathString("//*[@resource-id='de.eso.sound.audi:id/seats_menu_right_seat']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_CO_DRIVER_LEVEL_1 = XpathString("//*[@resource-id='de.eso.sound.audi:id/right_seat_headrest_level_1']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_CO_DRIVER_LEVEL_2 = XpathString("//*[@resource-id='de.eso.sound.audi:id/right_seat_headrest_level_2']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_CO_DRIVER_LEVEL_3 = XpathString("//*[@resource-id='de.eso.sound.audi:id/right_seat_headrest_level_3']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_CO_DRIVER_LEVEL_4 = XpathString("//*[@resource-id='de.eso.sound.audi:id/right_seat_headrest_level_4']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_CO_DRIVER_LEVEL_5 = XpathString("//*[@resource-id='de.eso.sound.audi:id/right_seat_headrest_level_5']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_DRIVER_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/seats_headrest_button_left']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_DRIVER_DECORATOR_IMAGE = XpathString("//*[@resource-id='de.eso.sound.audi:id/seats_menu_left_seat']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_DRIVER_LEVEL_1 = XpathString("//*[@resource-id='de.eso.sound.audi:id/left_seat_headrest_level_1']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_DRIVER_LEVEL_2 = XpathString("//*[@resource-id='de.eso.sound.audi:id/left_seat_headrest_level_2']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_DRIVER_LEVEL_3 = XpathString("//*[@resource-id='de.eso.sound.audi:id/left_seat_headrest_level_3']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_DRIVER_LEVEL_4 = XpathString("//*[@resource-id='de.eso.sound.audi:id/left_seat_headrest_level_4']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_DRIVER_LEVEL_5 = XpathString("//*[@resource-id='de.eso.sound.audi:id/left_seat_headrest_level_5']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_SLIDER = XpathString("//*[@resource-id='de.eso.sound.audi:id/sliderSeekBarAreaContainer']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_SLIDER_MAX_TEXT = XpathString("//*[@resource-id='de.eso.sound.audi:id/sliderSeekBarAreaContainer']/.//*[@content-desc='###de.eso.sound.audi:string/sound_seats__slider_max']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_SLIDER_MINUS_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/sliderSeekBarAreaContainer']/.//*[@resource-id='de.eso.sound.audi:id/minusButton']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_SLIDER_OFF_TEXT = XpathString("//*[@resource-id='de.eso.sound.audi:id/sliderSeekBarAreaContainer']/.//*[@content-desc='###de.eso.sound.audi:string/sound_seats__slider_min']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_SLIDER_PLUS_BUTTON = XpathString("//*[@resource-id='de.eso.sound.audi:id/sliderSeekBarAreaContainer']/.//*[@resource-id='de.eso.sound.audi:id/plusButton']")
PRESET_INDIVIDUAL_SEATS_PERSONAL_SURROUND_SOUND_SLIDER_SEEK_BAR = XpathString("//*[@resource-id='de.eso.sound.audi:id/sliderSeekBarAreaContainer']/.//*[@resource-id='de.eso.sound.audi:id/seekBar']")
PRESET_INDIVIDUAL_SURROUND_3D = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_surround__surround_3d']")
PRESET_INDIVIDUAL_SURROUND_3D_PLUS = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_surround__surround_3d_plus']")
PRESET_INDIVIDUAL_SURROUND_DEACTIVATED = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_surround__surround_deactivated']")
PRESET_INDIVIDUAL_SURROUND_EFFECT_IMAGE = XpathString("//*[@resource-id='de.eso.sound.audi:id/imgSurroundEffect']")
PRESET_INDIVIDUAL_SURROUND_SURROUNDSOUND = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_surround__surround']")
PRESET_INDIVIDUAL_SURROUND_SURROUNDSOUND_PLUS = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_surround__surround_plus']")

PRESETS_PRESET_EFFECT_IMAGE = XpathString("//*[@resource-id='de.eso.sound.audi:id/imgPresetEffectFront']")
PROVIDER_LOGO = XpathString("//*[@resource-id='de.eso.sound.audi:id/staticProviderLogoEndImageView']")

VOLUME_LIST_ITEM_ENT_LOWERING = XpathString("//*[@content-desc='###ListItemEntertainmentLowering']")
VOLUME_LIST_ITEM_ENT_LOWERING_LOW_BUTTON = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__toggle_group_item_entertainment_lowering_low']")
VOLUME_LIST_ITEM_ENT_LOWERING_MID_BUTTON = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__toggle_group_item_entertainment_lowering_mid']")
VOLUME_LIST_ITEM_ENT_LOWERING_OFF_BUTTON = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__toggle_group_item_entertainment_lowering_off']")
VOLUME_LIST_ITEM_ENT_LOWERING_STRONG_BUTTON = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__toggle_group_item_entertainment_lowering_strong']")
VOLUME_LIST_ITEM_ENT_LOWERING_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_entertainment_lowering']")
VOLUME_LIST_ITEM_NAV_ANNOUNCEMENT = XpathString("//*[@content-desc='###ListItemNavigationAnnoucement']")
VOLUME_LIST_ITEM_NAV_ANNOUNCEMENT_MAX_TEXT = XpathString("//*[@content-desc='###ListItemNavigationAnnoucement']/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_max']")
VOLUME_LIST_ITEM_NAV_ANNOUNCEMENT_MINUS_BUTTON = XpathString("//*[@content-desc='###ListItemNavigationAnnoucement-minusButton']")
VOLUME_LIST_ITEM_NAV_ANNOUNCEMENT_OFF_TEXT = XpathString("//*[@content-desc='###ListItemNavigationAnnoucement']/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_off']")
VOLUME_LIST_ITEM_NAV_ANNOUNCEMENT_PLUS_BUTTON = XpathString("//*[@content-desc='###ListItemNavigationAnnoucement-plusButton']")
VOLUME_LIST_ITEM_NAV_ANNOUNCEMENT_SEEK_BAR = XpathString("//*[@content-desc='###ListItemNavigationAnnoucement-seekBar']")
VOLUME_LIST_ITEM_NAV_ANNOUNCEMENT_TEXT = XpathString("//*[@content-desc='###ListItemNavigationAnnoucement']/.//*[@content-desc='###listItemText']")
VOLUME_LIST_ITEM_OSD = XpathString("//*[@content-desc='###ListItemOpenSourceDisclaimer']")
VOLUME_LIST_ITEM_OSD_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_open_source_disclaimer']")
VOLUME_LIST_ITEM_PERSONAL_NAV_ANNOUNCEMENT = XpathString("//*[@content-desc='###ListItemPersonalNavAnnouncement']")
VOLUME_LIST_ITEM_PERSONAL_NAV_ANNOUNCEMENT_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_personal_nav_announcement']")
VOLUME_LIST_ITEM_PERSONAL_NAV_ANNOUNCEMENT_TOGGLE_BUTTON = XpathString("//*[@content-desc='###ListItemPersonalNavAnnouncement-switch']")
VOLUME_LIST_ITEM_SPEED_DEPENDENT_VOLUME = XpathString("//*[@content-desc='###ListItemSpeedDependentVolume']")
VOLUME_LIST_ITEM_SPEED_DEPENDENT_VOLUME_MAX_TEXT = XpathString("//*[@content-desc='###ListItemSpeedDependentVolume']/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_max']")
VOLUME_LIST_ITEM_SPEED_DEPENDENT_VOLUME_MINUS_BUTTON = XpathString("//*[@content-desc='###ListItemSpeedDependentVolume-minusButton']")
VOLUME_LIST_ITEM_SPEED_DEPENDENT_VOLUME_OFF_TEXT = XpathString("//*[@content-desc='###ListItemSpeedDependentVolume']/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_off']")
VOLUME_LIST_ITEM_SPEED_DEPENDENT_VOLUME_PLUS_BUTTON = XpathString("//*[@content-desc='###ListItemSpeedDependentVolume-plusButton']")
VOLUME_LIST_ITEM_SPEED_DEPENDENT_VOLUME_SEEK_BAR = XpathString("//*[@content-desc='###ListItemSpeedDependentVolume-seekBar']")
VOLUME_LIST_ITEM_SPEED_DEPENDENT_VOLUME_TEXT = XpathString("//*[@content-desc='###ListItemSpeedDependentVolume']/.//*[@content-desc='###listItemText']")
VOLUME_LIST_ITEM_SYSTEM_SOUND = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement'])[2]")
VOLUME_LIST_ITEM_SYSTEM_SOUND_MAX_TEXT = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement'])[2]/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_max']")
VOLUME_LIST_ITEM_SYSTEM_SOUND_MINUS_BUTTON = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement-minusButton'])[2]")
VOLUME_LIST_ITEM_SYSTEM_SOUND_OFF_TEXT = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement'])[2]/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_off']")
VOLUME_LIST_ITEM_SYSTEM_SOUND_PLUS_BUTTON = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement-plusButton'])[2]")
VOLUME_LIST_ITEM_SYSTEM_SOUND_SEEK_BAR = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement-seekBar'])[2]")
VOLUME_LIST_ITEM_SYSTEM_SOUND_TEXT = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement'])[2]/.//*[@content-desc='###listItemText']")
VOLUME_LIST_ITEM_SYSTEM_SOUND_SUB_TEXT = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement'])[2]/.//*[@content-desc='###listItemSubText']")
VOLUME_LIST_ITEM_TRAFFIC_ANNOUNCEMENT = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement'])[1]")
VOLUME_LIST_ITEM_TRAFFIC_ANNOUNCEMENT_MAX_TEXT = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement'])[1]/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_max']")
VOLUME_LIST_ITEM_TRAFFIC_ANNOUNCEMENT_MINUS_BUTTON = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement-minusButton'])[1]")
VOLUME_LIST_ITEM_TRAFFIC_ANNOUNCEMENT_OFF_TEXT = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement'])[1]/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_off']")
VOLUME_LIST_ITEM_TRAFFIC_ANNOUNCEMENT_PLUS_BUTTON = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement-plusButton'])[1]")
VOLUME_LIST_ITEM_TRAFFIC_ANNOUNCEMENT_SEEK_BAR = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement-seekBar'])[1]")
VOLUME_LIST_ITEM_TRAFFIC_ANNOUNCEMENT_TEXT = XpathString("(//*[@content-desc='###ListItemTrafficAnnouncement'])[1]/.//*[@content-desc='###listItemText']")
VOLUME_LIST_ITEM_VOICE_COMMAND_ANNOUNCEMENT = XpathString("//*[@content-desc='###ListItemVoiceCommandAnnouncement']")
VOLUME_LIST_ITEM_VOICE_COMMAND_ANNOUNCEMENT_MAX_TEXT = XpathString("//*[@content-desc='###ListItemVoiceCommandAnnouncement']/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_max']")
VOLUME_LIST_ITEM_VOICE_COMMAND_ANNOUNCEMENT_MINUS_BUTTON = XpathString("//*[@content-desc='###ListItemVoiceCommandAnnouncement-minusButton']")
VOLUME_LIST_ITEM_VOICE_COMMAND_ANNOUNCEMENT_OFF_TEXT = XpathString("//*[@content-desc='###ListItemVoiceCommandAnnouncement']/.//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_slider_off']")
VOLUME_LIST_ITEM_VOICE_COMMAND_ANNOUNCEMENT_PLUS_BUTTON = XpathString("//*[@content-desc='###ListItemVoiceCommandAnnouncement-plusButton']")
VOLUME_LIST_ITEM_VOICE_COMMAND_ANNOUNCEMENT_SEEK_BAR = XpathString("//*[@content-desc='###ListItemVoiceCommandAnnouncement-seekBar']")
VOLUME_LIST_ITEM_VOICE_COMMAND_ANNOUNCEMENT_TEXT = XpathString("//*[@content-desc='###ListItemVoiceCommandAnnouncement']/.//*[@content-desc='###listItemText']")
VOLUME_LIST_ITEM_WELCOME_SOUND = XpathString("//*[@content-desc='###ListItemVolumeWelcomeSound']")
VOLUME_LIST_ITEM_WELCOME_SOUND_TEXT = XpathString("//*[@content-desc='###de.eso.sound.audi:string/sound_settings__list_item_volume_welcome_sound']")
VOLUME_LIST_ITEM_WELCOME_SOUND_TOGGLE_BUTTON = XpathString("//*[@content-desc='###ListItemVolumeWelcomeSound-switch']")
