# coding=utf-8
# pylint: disable=line-too-long,too-many-lines,invalid-character-zero-width-space,invalid-name,redefined-builtin
"""Module contains Text Objects"""
from enna_hcp_configuration.texts import TextObject

generic_error_blocking__text = TextObject(bs_BA="Ograničeno rukovanje u toku vožnje.", cs_CZ="Omezená obsluha během jízdy.", da_DK="Begrænset betjening under kørsel.", de_DE="Eingeschränkte Bedienung während der Fahrt.", el_GR="Περιορισμένος χειρισμός κατά τη διάρκεια της οδήγησης.", en_GB="For your safety, limited operation while driving.", es_ES="Manejo limitado durante la marcha.", fi_FI="Rajoitettu käyttö ajon aikana.", fr_FR="Utilisation restreinte pendant la conduite.", hr_HR="Ograničeno rukovanje tijekom vožnje.", hu_HU="Korlátozott használat menet közben.", it_IT="Utilizzo limitato durante la marcia.", nl_NL="Beperkte bediening tijdens het rijden.", no_NO="Betjening er begrenset under kjøring.", pl_PL="Ograniczona obsługa podczas jazdy.", pt_PT="Acionamento com restrições durante a circulação.", ro_RO="Operare limitată în timpul deplasării.", ru_RU="Во время движения управление ограничено.", sk_SK="Obmedzená obsluha počas jazdy.", sl_SI="Omejeno upravljanje med vožnjo.", sr_RS="Ograničeno rukovanje u toku vožnje.", sv_SE="Begränsad användning under körning.", tr_TR="Sürüş sırasında sınırlı kullanım.", uk_UA="Під час руху керування обмежено.")
mediator_osd__app_name = TextObject(bs_BA="Proizvod - Service connect", cs_CZ="Produkt-Service connect", da_DK="Produktservice connect", de_DE="Produkt-Service connect", el_GR="Προϊον-Service connect", en_GB="Product service for connect", es_ES="Producto - Servicio connect", fi_FI="Connect-tuotepalvelu", fr_FR="Service produit connect", hr_HR="Proizvod-Service connect", hu_HU="Termék/szolgáltatás kapcsolat", it_IT="Servizio prodotto connect", nl_NL="Productservice connect", no_NO="Produktservice connect", pl_PL="Usługa produktu connect", pt_PT="Produto Service connect", ro_RO="Produs service connect", ru_RU="Продукт-сервис connect", sk_SK="Produkt-Service connect", sl_SI="Produkt-Service connect", sr_RS="Proizvod - Service connect", sv_SE="Produktservice connect", tr_TR="connect ürün servisi", uk_UA="Продукт-сервіс connect")
mediator_osd__back__content_description = TextObject(bs_BA="Nazad", cs_CZ="Zpět", da_DK="Tilbage", de_DE="Zurück", el_GR="Πίσω", en_GB="Back", es_ES="Atrás", fi_FI="Takaisin", fr_FR="Retour", hr_HR="Natrag", hu_HU="Vissza", it_IT="Indietro", nl_NL="Terug", no_NO="Tilbake", pl_PL="Powrót", pt_PT="Retroceder", ro_RO="Înapoi", ru_RU="Назад", sk_SK="Späť", sl_SI="Nazaj", sr_RS="Nazad", sv_SE="Tillbaka", tr_TR="Geri", uk_UA="Назад")
mediator_osd__scroll_to_top_button__content_description = TextObject(bs_BA="Idi na početak", cs_CZ="Na začátek", da_DK="Til toppen", de_DE="Zum Anfang", el_GR="Μετάβαση στην αρχή", en_GB="To top", es_ES="Ir a Inicio", fi_FI="Siirry alkuun", fr_FR="Retour au début", hr_HR="Na početak", hu_HU="Az elejére", it_IT="Vai all'inizio", nl_NL="Begin", no_NO="Til starten", pl_PL="Do początku", pt_PT="Para o inicio", ro_RO="Spre început", ru_RU="В начало", sk_SK="Na začiatok", sl_SI="Na začetek", sr_RS="Idi na početak", sv_SE="Till början", tr_TR="Başlangıca git", uk_UA="На початок")
mediator_osd__title_activity_osd_settings = TextObject(bs_BA="Open Source Software Notice", cs_CZ="Open Source Software Notice", da_DK="Open Source Software Notice", de_DE="Open Source Software Notice", el_GR="Open Source Software Notice", en_GB="Open Source Software Notice", es_ES="Open Source Software Notice", fi_FI="Open Source Software Notice", fr_FR="Open Source Software Notice", hr_HR="Open Source Software Notice", hu_HU="Open Source Software Notice", it_IT="Open Source Software Notice", nl_NL="Open Source Software Notice", no_NO="Open Source Software Notice", pl_PL="Open Source Software Notice", pt_PT="Open Source Software Notice", ro_RO="Open Source Software Notice", ru_RU="Open Source Software Notice", sk_SK="Open Source Software Notice", sl_SI="Open Source Software Notice", sr_RS="Open Source Software Notice", sv_SE="Open Source Software Notice", tr_TR="Open Source Software Notice", uk_UA="Open Source Software Notice")
mediator_service_title__label = TextObject(bs_BA="Proizvod - Service connect", cs_CZ="Produkt-Service connect", da_DK="Produktservice connect", de_DE="Produkt-Service connect", el_GR="Προϊον-Service connect", en_GB="Product service for connect", es_ES="Producto - Servicio connect", fi_FI="Connect-tuotepalvelu", fr_FR="Service produit connect", hr_HR="Proizvod-Service connect", hu_HU="Termék/szolgáltatás kapcsolat", it_IT="Servizio prodotto connect", nl_NL="Productservice connect", no_NO="Produktservice connect", pl_PL="Usługa produktu connect", pt_PT="Produto Service connect", ro_RO="Produs service connect", ru_RU="Продукт-сервис connect", sk_SK="Produkt-Service connect", sl_SI="Produkt-Service connect", sr_RS="Proizvod - Service connect", sv_SE="Produktservice connect", tr_TR="connect ürün servisi", uk_UA="Продукт-сервіс connect")
mediator_settings_screen__open_source_license__title = TextObject(bs_BA="Open Source Software Notice", cs_CZ="Open Source Software Notice", da_DK="Open Source Software Notice", de_DE="Open Source Software Notice", el_GR="Open Source Software Notice", en_GB="Open Source Software Notice", es_ES="Open Source Software Notice", fi_FI="Open Source Software Notice", fr_FR="Open Source Software Notice", hr_HR="Open Source Software Notice", hu_HU="Open Source Software Notice", it_IT="Open Source Software Notice", nl_NL="Open Source Software Notice", no_NO="Open Source Software Notice", pl_PL="Open Source Software Notice", pt_PT="Open Source Software Notice", ro_RO="Open Source Software Notice", ru_RU="Open Source Software Notice", sk_SK="Open Source Software Notice", sl_SI="Open Source Software Notice", sr_RS="Open Source Software Notice", sv_SE="Open Source Software Notice", tr_TR="Open Source Software Notice", uk_UA="Open Source Software Notice")
